### ISSUE TITLE
Youtube wallpaper doesn't proceed or does nothing

### ISSUE THREAD

**Issue by kuroshiropanda** [rocksdanister/lively#102]
**Describe the bug**
Adding a youtube wallpaper does nothing or doesn't proceed to creating it as a wallpaper

**To Reproduce**
1. drag and drop a youtube video
2. does nothing

**Expected behavior**
It should proceed and create a youtube wallpaper

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
- Which wallpaper was running at the time if any: none

**Log file**
```
2020-08-19 01:55:06.1594|INFO|livelywpf.SystemInfo|Lively v0.9.6.0 en-US  64Bit:False
2020-08-19 01:55:06.1789|INFO|livelywpf.SystemInfo|Portable build: False
2020-08-19 01:55:06.2799|INFO|livelywpf.SystemInfo|OS: Microsoft Windows 10 Pro 10.0.19041
2020-08-19 01:55:07.3595|INFO|livelywpf.SystemInfo|CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
2020-08-19 01:55:07.3855|INFO|livelywpf.SystemInfo|GPU: NVIDIA GeForce GTX 1060 6GB
2020-08-19 01:55:08.0200|DEBUG|livelywpf.MainWindow|Detected Displays:- Screen[Bounds={X=0,Y=0,Width=1366,Height=768} WorkingArea={X=0,Y=0,Width=1366,Height=768} Primary=True DeviceName=\\.\DISPLAY1
2020-08-19 01:55:08.0200|DEBUG|livelywpf.MainWindow|Detected Displays:- Screen[Bounds={X=-1366,Y=0,Width=1366,Height=768} WorkingArea={X=-1366,Y=0,Width=1366,Height=738} Primary=False DeviceName=\\.\DISPLAY2
2020-08-19 01:55:08.0495|INFO|livelywpf.MainWindow|Restarting/Restoring All Wallpaper(s)
2020-08-19 01:55:14.2190|INFO|livelywpf.MainWindow|Loading Wallpaper (wp dir):- E:\Documents\Lively Wallpaper\wallpapers\242tny3g.eod\index.html web_audio
2020-08-19 01:55:14.2410|INFO|livelywpf.MainWindow|Loading Wallpaper (wp dir):- E:\Documents\Lively Wallpaper\wallpapers\2elw0opr.keh\index.html web
2020-08-19 01:55:14.2410|INFO|livelywpf.MainWindow|Loading Wallpaper (wp dir):- E:\Documents\Lively Wallpaper\wallpapers\djcze13f.mlq\eternal_light_version2.mp4 video
2020-08-19 01:55:14.2920|INFO|livelywpf.MainWindow|Loading Wallpaper (wp dir):- E:\Documents\Lively Wallpaper\wallpapers\fcyn5jal.wj2\index.html web
2020-08-19 01:55:14.3015|INFO|livelywpf.MainWindow|Loading Wallpaper (wp dir):- E:\Documents\Lively Wallpaper\wallpapers\gyl1gr5r.hq4\waves.html web
2020-08-19 01:55:14.3015|INFO|livelywpf.MainWindow|Loading Wallpaper (wp dir):- E:\Documents\Lively Wallpaper\wallpapers\gzmbwao1.2ii\index.html web
2020-08-19 01:55:14.3135|INFO|livelywpf.MainWindow|Loading Wallpaper (wp dir):- E:\Documents\Lively Wallpaper\wallpapers\huryleus.43p\index.html web
2020-08-19 01:55:14.3135|INFO|livelywpf.MainWindow|Loading Wallpaper (wp dir):- E:\Documents\Lively Wallpaper\wallpapers\kjmvxfbx.epw\cinemagraph.mp4 video
2020-08-19 01:55:14.3325|INFO|livelywpf.MainWindow|Loading Wallpaper (wp dir):- E:\Documents\Lively Wallpaper\wallpapers\s1qdxgqn.hhx\index.html web
2020-08-19 01:55:14.3325|INFO|livelywpf.MainWindow|Loading Wallpaper (wp dir):- E:\Documents\Lively Wallpaper\wallpapers\upqwyiur.c4g\index.html web
2020-08-19 01:55:25.2021|INFO|livelywpf.MainWindow|Dropped Text:- https://www.youtube.com/watch?v=RQA5RcIZlAM
2020-08-19 01:55:26.4799|INFO|livelywpf.MainWindow|Setting up wallpaper:-https://www.youtube.com/watch?v=RQA5RcIZlAM
2020-08-19 01:55:26.6474|INFO|livelywpf.SetupDesktop|app crashed/terminated early(2):System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_MainWindowHandle()
   at livelywpf.SetupDesktop.<WaitForProcesWindow>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at livelywpf.SetupDesktop.<SetWallpaper>d__34.MoveNext()
2020-08-19 01:55:26.6474|ERROR|livelywpf.SetupDesktop|System.InvalidOperationException: Cannot process request because the process (21328) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at livelywpf.SetupDesktop.<SetWallpaper>d__34.MoveNext()
2020-08-19 01:55:27.1816|INFO|livelywpf.SetupDesktop|searching workerWOrig..
2020-08-19 01:55:27.1891|INFO|livelywpf.SetupDesktop|searching again shell_tray..
2020-08-19 02:01:09.3530|INFO|livelywpf.MainWindow|Dropped Text:- https://www.youtube.com/watch?v=1K1EmfqYl_8
2020-08-19 02:01:10.6590|INFO|livelywpf.MainWindow|Setting up wallpaper:-https://www.youtube.com/watch?v=1K1EmfqYl_8
2020-08-19 02:01:10.7820|INFO|livelywpf.SetupDesktop|app crashed/terminated early(2):System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_MainWindowHandle()
   at livelywpf.SetupDesktop.<WaitForProcesWindow>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at livelywpf.SetupDesktop.<SetWallpaper>d__34.MoveNext()
2020-08-19 02:01:10.7820|ERROR|livelywpf.SetupDesktop|System.InvalidOperationException: Cannot process request because the process (20140) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at livelywpf.SetupDesktop.<SetWallpaper>d__34.MoveNext()
2020-08-19 02:01:12.7825|INFO|livelywpf.MainWindow|Dropped Text:- https://www.youtube.com/watch?v=1K1EmfqYl_8
2020-08-19 02:01:13.4448|INFO|livelywpf.MainWindow|Setting up wallpaper:-https://www.youtube.com/watch?v=1K1EmfqYl_8
2020-08-19 02:01:13.5718|INFO|livelywpf.SetupDesktop|app crashed/terminated early(2):System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_MainWindowHandle()
   at livelywpf.SetupDesktop.<WaitForProcesWindow>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at livelywpf.SetupDesktop.<SetWallpaper>d__34.MoveNext()
2020-08-19 02:01:13.5718|ERROR|livelywpf.SetupDesktop|System.InvalidOperationException: Cannot process request because the process (30396) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at livelywpf.SetupDesktop.<SetWallpaper>d__34.MoveNext()
2020-08-19 02:01:15.2965|INFO|livelywpf.MainWindow|Dropped Text:- https://www.youtube.com/watch?v=1K1EmfqYl_8
2020-08-19 02:01:15.9696|INFO|livelywpf.MainWindow|Setting up wallpaper:-https://www.youtube.com/watch?v=1K1EmfqYl_8
2020-08-19 02:01:16.1036|INFO|livelywpf.SetupDesktop|app crashed/terminated early(2):System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_MainWindowHandle()
   at livelywpf.SetupDesktop.<WaitForProcesWindow>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at livelywpf.SetupDesktop.<SetWallpaper>d__34.MoveNext()
2020-08-19 02:01:16.1106|ERROR|livelywpf.SetupDesktop|System.InvalidOperationException: Cannot process request because the process (8596) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at livelywpf.SetupDesktop.<SetWallpaper>d__34.MoveNext()
2020-08-19 02:02:01.5943|INFO|livelywpf.MainWindow|Dropped Text:- https://www.youtube.com/watch?v=1K1EmfqYl_8
2020-08-19 02:02:02.9541|INFO|livelywpf.MainWindow|Setting up wallpaper:-https://www.youtube.com/watch?v=1K1EmfqYl_8
2020-08-19 02:02:03.1391|INFO|livelywpf.SetupDesktop|app crashed/terminated early(2):System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_MainWindowHandle()
   at livelywpf.SetupDesktop.<WaitForProcesWindow>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at livelywpf.SetupDesktop.<SetWallpaper>d__34.MoveNext()
2020-08-19 02:02:03.1446|ERROR|livelywpf.SetupDesktop|System.InvalidOperationException: Cannot process request because the process (25984) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at livelywpf.SetupDesktop.<SetWallpaper>d__34.MoveNext()
2020-08-19 02:03:59.5454|INFO|livelywpf.MainWindow|Dropped Text:- https://www.youtube.com/watch?v=1K1EmfqYl_8
2020-08-19 02:04:00.5615|INFO|livelywpf.MainWindow|Setting up wallpaper:-https://www.youtube.com/watch?v=1K1EmfqYl_8
2020-08-19 02:04:00.6865|INFO|livelywpf.SetupDesktop|app crashed/terminated early(2):System.InvalidOperationException: Process has exited, so the requested information is not available.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_MainWindowHandle()
   at livelywpf.SetupDesktop.<WaitForProcesWindow>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at livelywpf.SetupDesktop.<SetWallpaper>d__34.MoveNext()
2020-08-19 02:04:00.6865|ERROR|livelywpf.SetupDesktop|System.InvalidOperationException: Cannot process request because the process (5732) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at livelywpf.SetupDesktop.<SetWallpaper>d__34.MoveNext()
```

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Youtube-Wallpaper
1. Are you using the same version of mpv given in the instructions?
2. Is Microsoft Visual C++ 2010 installed?
3. What happens when you drop the youtube link into mpv player window directly?

**Comment by kuroshiropanda** [comment]
> Are you using the same version of mpv given in the instructions?

yes

> Is Microsoft Visual C++ 2010 installed?

a newer version is installed it says when I installed the one linked on the wiki

> What happens when you drop the youtube link into mpv player window directly?

it plays the youtube video normally.
using youtube-dl to download the youtube url works normally too.

**Comment by kuroshiropanda** [comment]
can be fixed by setting the stream video quality to best
other quality options crashes it

**Comment by rocksdanister** [comment]
So its the problem with the arguments I'm sending to mpc hmm.

```"\"" + link + "\"" + " --force-window=yes --loop-file --keep-open --hwdec=yes --no-keepaspect" + " --ytdl-format bestvideo[height<=1440]+bestaudio/best[height<=1440]"```

Lively v1.0 is using libVLC to directly play streams, so this should not be an issue hopefully.
