### ISSUE TITLE
[Bug]: The taskbar cannot set Gaussian blur and other effects

### ISSUE THREAD

**Issue by daizihan233** [rocksdanister/lively#1143]
English is not my native language; please excuse typing errors.
**Describe the bug**
The taskbar cannot set Gaussian blur and other effects, but it looks like in V2.0.0.1 version has been completed.

**To Reproduce**
![image](https://user-images.githubusercontent.com/72146468/159253387-46ad46ad-1f18-41fa-a0b6-9456d69e1bee.png)
I try to open the debugger to find the problem. The above is the log I intercepted. No matter how to change the effect, my taskbar still looks the same as when the effect is turned off.

**Expected behavior**
The effect should be different.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/72146468/159254089-76855f5b-831a-4e7a-8f2c-92df66f66db3.png)
![image](https://user-images.githubusercontent.com/72146468/159254115-478babf3-f9da-4b00-ada4-c6a34af54d41.png)
![image](https://user-images.githubusercontent.com/72146468/159254142-bc7b7361-d2fe-419d-94ce-c4f87acb5ec4.png)
![image](https://user-images.githubusercontent.com/72146468/159254166-503511ab-5c50-4cc1-81e4-3fa1c93427d7.png)
![image](https://user-images.githubusercontent.com/72146468/159254200-1c27ebb8-a6fd-48eb-8ba6-debaf80b2d76.png)
![image](https://user-images.githubusercontent.com/72146468/159254231-094d5cc3-895b-4e6f-9aab-eb72ddeac127.png)
No matter how you switch, you can see that the taskbar at the bottom is no different.
**Desktop (please complete the following information):**
 - OS: Windows 11 home Chinese (22579.1) **Note: this system belongs to dev channel**
- Download wallpaper from here: [removed] (Note: This is true for any wallpaper)

**Additional context**
The software version is v2 0.0.1, the version downloaded in GitHub release

**Log file (Important)**
```
2022-03-21 19:51:00.8107|INFO|Lively.App|
Lively v2.0.0.1 x64 desktop-native zh-CN
OS: Microsoft Windows 11 家庭中文版 10.0.22579
CPU: Intel(R) Core(TM) i5-10200H CPU @ 2.40GHz
GPU: NVIDIA GeForce GTX 1650
GPU: Intel(R) UHD Graphics

2022-03-21 19:51:01.0988|INFO|Lively.Services.TranslucentTBService|Taskbar theme: fluent
2022-03-21 19:51:01.1194|INFO|Lively.Services.TranslucentTBService|Taskbar theme service started.
2022-03-21 19:51:02.1415|INFO|Lively.Core.WinDesktopCore|Restoring wallpaper 《神明的对话日记》 | C:\Users\HanTools\AppData\Local\Lively Wallpaper\Library\SaveData\wptmp\g0d1ztna.mh2
2022-03-21 19:51:02.1415|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: 《神明的对话日记》 | D:\迅雷下载\550342528_u1-1-116.flv
2022-03-21 19:51:02.1929|INFO|Lively.Core.WinDesktopCore|Core initialized..
2022-03-21 19:51:02.1929|INFO|Lively.Core.Watchdog.WatchdogProcess|Starting watchdog service...
2022-03-21 19:51:03.2419|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0:  (+) Video --vid=1 (h264 1920x1080 60.000fps)
2022-03-21 19:51:03.2419|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0:  (+) Audio --aid=1 (aac 2ch 48000Hz)
2022-03-21 19:51:03.2419|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0: File tags:
2022-03-21 19:51:03.2419|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0:  Description: Bilibili VXCode Swarm Transcoder v0.7.3
2022-03-21 19:51:03.4893|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0: Using hardware decoding (d3d11va).
2022-03-21 19:51:03.8907|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0: AO: [wasapi] 48000Hz stereo 2ch float
2022-03-21 19:51:03.8907|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0: VO: [gpu] 1920x1080 d3d11[nv12]
2022-03-21 19:51:03.9345|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=1920,Height=1080}
2022-03-21 19:51:03.9828|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 6624
2022-03-21 19:51:06.2829|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0: Audio/Video desynchronisation detected! Possible reasons include too slow
2022-03-21 19:51:06.2829|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0: hardware, temporary CPU spikes, broken drivers, and broken files. Audio
2022-03-21 19:51:06.2829|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0: position will not match to the video (see A-V status field).
2022-03-21 19:51:08.2900|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0: Audio device underrun detected.
2022-03-21 19:51:33.2750|ERROR|Lively.App|System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Cannot access a closed pipe.)
 ---> System.ObjectDisposedException: Cannot access a closed pipe.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.WriteTo(Stream stream)
   at GrpcDotNetNamedPipes.Internal.NamedPipeTransport.WriteTransaction.Commit()
   at GrpcDotNetNamedPipes.Internal.ServerConnectionContext.WriteTrailers(StatusCode statusCode, String statusDetail)
   at GrpcDotNetNamedPipes.Internal.ServerConnectionContext.Error(Exception ex)
   at GrpcDotNetNamedPipes.NamedPipeServer.ServiceBinderImpl.<>c__DisplayClass2_0`2.<<AddMethod>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at GrpcDotNetNamedPipes.Internal.ServerConnectionContext.<>c__DisplayClass29_0.<<HandleRequestInit>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
2022-03-21 19:51:33.5758|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0: Audio device underrun detected.
```

**Comment by rocksdanister** [comment]
Duplicate: https://github.com/rocksdanister/lively/issues/1084
Will have to wait and see how stable build turns out.
