### ISSUE TITLE
Cannot get Lively to set a wallpaper: Animate control elements settings error.

### ISSUE THREAD

**Issue by PapierenTijger** [rocksdanister/lively#135]
![Lively](https://user-images.githubusercontent.com/49154288/92989024-45866800-f4d1-11ea-86d2-029e5079850d.png)
**Before proceeding**
Check the [Wiki](https://github.com/rocksdanister/lively/wiki) and [Issues](https://github.com/rocksdanister/lively/issues?q=is%3Aopen+is%3Aissue) to see if your problem is already addressed.

**Describe the bug**
Cannot set a wallpaper right after installing Lively

**To Reproduce**
1. Go to Lively in system tray as it is asked for during installation
2. Click on any wallpaper in the gallery
3. Error message from screenshot pops up
4. Contrary to what the error believes *Animate controls...* is enabled

**Expected behavior**
Wallpaper should be set

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 2004 (19041.508) 
- Just the default Windows wallpaper was set 

**Additional context**
- I ran Lively in Windows Sandbox - probably it has something to do with that.
- The error message starts with asking to *Open This PC*. I was first opening the Start menu. Maybe you should ask for something like *Click on This PC in File Explorer*.

**Log file**
2020-09-12 08:37:22.6717|INFO|livelywpf.NLogger|
Lively v1.0.7.0 en-US 64Bit:False
OS: Microsoft Windows 10 Enterprise 10.0.19041
CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
GPU: Microsoft Remote Display Adapter

2020-09-12 08:37:22.7166|ERROR|livelywpf.SettingsJSON|System.IO.FileNotFoundException: Could not find file 'C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Settings.json'.
File name: 'C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Settings.json'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at livelywpf.SettingsJSON.LoadConfig(String filePath) in C:\Users\rocks\source\repos\livelywpf\livelywpf\DataJSON\SettingsJSON.cs:line 17
2020-09-12 08:37:23.7230|ERROR|livelywpf.ApplicationRulesJSON|System.IO.FileNotFoundException: Could not find file 'C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\AppRules.json'.
File name: 'C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\AppRules.json'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at livelywpf.ApplicationRulesJSON.LoadAppRules(String filePath) in C:\Users\rocks\source\repos\livelywpf\livelywpf\DataJSON\ApplicationRulesJSON.cs:line 49
2020-09-12 08:37:23.7592|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Library\wallpapers\0wj1biqk.f41\fluid.html webaudio
2020-09-12 08:37:23.7592|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Library\wallpapers\3flakw30.bpx\outrun.html web
2020-09-12 08:37:23.7592|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Library\wallpapers\aahrtq0t.dme\index.html web
2020-09-12 08:37:23.7592|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Library\wallpapers\gdkyowfb.3tk\eternal_light_version2.mp4 video
2020-09-12 08:37:23.7592|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Library\wallpapers\iqdvd4pt.jyo\triangle.html web
2020-09-12 08:37:23.7592|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Library\wallpapers\lgz4xpht.sjn\index.html web
2020-09-12 08:37:23.7592|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Library\wallpapers\mrn3a0m5.0lk\index.html web
2020-09-12 08:37:23.7592|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Library\wallpapers\nps35xrp.5eh\jellyfish.html web
2020-09-12 08:37:23.7592|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Library\wallpapers\ptpcxvcd.hlz\index.html web
2020-09-12 08:37:23.7592|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Library\wallpapers\rtnm43pj.wyl\index.html web
2020-09-12 08:37:23.7592|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Library\wallpapers\v44be4yd.a1r\ribbon.html web
2020-09-12 08:37:23.7656|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2\index.html web
2020-09-12 08:37:23.7656|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\Library\wallpapers\zddkyl1e.gkl\starfield.html web
2020-09-12 08:37:24.5317|ERROR|livelywpf.WallpaperLayoutJSON|System.IO.FileNotFoundException: Could not find file 'C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\WallpaperLayout.json'.
File name: 'C:\Users\WDAGUtilityAccount\AppData\Local\Lively Wallpaper\WallpaperLayout.json'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at livelywpf.WallpaperLayoutJSON.LoadWallpaperLayout(String filePath) in C:\Users\rocks\source\repos\livelywpf\livelywpf\DataJSON\WallpaperLayoutJSON.cs:line 49
2020-09-12 08:37:37.7264|ERROR|livelywpf.SetupDesktop|Failed to setup wallpaper, WorkerW handle null!
2020-09-12 08:38:04.2225|ERROR|livelywpf.SetupDesktop|Failed to setup wallpaper, WorkerW handle null!

**Comment by rocksdanister** [comment]
Both the videoplayer and web browser uses hardware acceleration, it will be most likely slow in sandbox.

So recently I noticed that accessing the Performance Options that way only changes for the admin(?) account and not the current account from which the menu is accessed.
I have updated info on wiki:
https://github.com/rocksdanister/lively/wiki/Getting-Started

`Press the Win + R keys to open Run, type SystemPropertiesPerformance.exe into Run, click on "OK" to open Performance Options.`

Tested working in sandbox:
![sandbox](https://user-images.githubusercontent.com/17554161/92989794-7a57e680-f4f4-11ea-9a0d-01375b1e0d0d.png)

(You can attach the txt file instead 😅)

**Comment by PapierenTijger** [comment]
I got it to work with `SystemPropertiesPerformance.exe`. The *Animate controls* was enabled and it still wouldn't work, but I toggled it off (Click Apply) and on again (Click Apply). Then it worked. Thanks for the quick reply and I like it :)
