### ISSUE TITLE
Wont auto-start and crashes when waking from sleep mode

### ISSUE THREAD

**Issue by frostytokes** [rocksdanister/lively#1378]
[lively_log_20220907_010908.zip](https://github.com/rocksdanister/lively/files/9504091/lively_log_20220907_010908.zip)
 
Lively wont auto-start even when option is enabled, but will start and display wallpapers fine when manually started. Will also crash upon waking from sleep mode. Was not an issue before v2.0.3.2

**Comment by rocksdanister** [comment]
There are two issues here:

```
2022-09-07 01:08:32.8511|ERROR|Lively.App|System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
   at Lively.RPC.DisplayManagerServer.<>c__DisplayClass4_0.<SubscribeDisplayChanged>g__DisplayChanged|0(Object s, EventArgs e) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\RPC\DisplayManagerServer.cs:line 78
```
   
this issue is fixed https://github.com/rocksdanister/lively/commit/a031c9a2271955070ad3fb2fc9a35482639f6948 and currently being tested on beta channel.

```
2022-09-07 01:08:59.3505|ERROR|Lively.Core.WinDesktopCore|Failed to setup core, WorkerW handle not found..
```

this error usually happens when you have other applications that modify desktop, do you use any software like Fences.. etc?

**Comment by frostytokes** [comment]
not that i can see. i use roblox fps unblocker sometimes and nvidia's in game overlay, but i dont know if either of those would count. But if they dont then lively is pretty much the only app i use that changes my desktop. is there anything you think i can do on my end?

**Comment by Asturias76** [comment]
Hello, I have the same issue. I have 2 screens and sometimes, after sleep mode, one or both screens don't have the dynamic wallpapers running (I use Fluids). I have to open Lively, close active screens (next to "+ Add") and choose again Fluids. Otherwise, its a great software, I really like it :).

**Comment by frostytokes** [comment]
not that i can see. i use roblox fps unblocker sometimes and nvidia's in
game overlay, but i dont know if either of those would count. But if they
dont then lively is pretty much the only app i use that changes my desktop.
is there anything you think i can do on my end?

**Comment by 79845** [comment]
I have Lively to auto start with windows 11, but I always have to mannualy start it for it to work. What can I do to fix this? Thanks!

[lively_log_20230702_051746.zip](https://github.com/rocksdanister/lively/files/11928985/lively_log_20230702_051746.zip)
