### ISSUE TITLE
(BUG) Lively Does not seem to want open the GUI at all.

### ISSUE THREAD

**Issue by knightryry** [rocksdanister/lively#1409]
**Describe the bug**
The bug seems to make the Lively UI Crash on launch.
No Error are spat out user side.

**To Reproduce**
1. Right Click Lively from the tray.
2. Press Open Lively.
3. Nothing Appears after a few min. 
**Expected behavior**
The Lively UI should appear after pressing open lively
**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2 OS Build 19044.2006

- Which wallpaper was running at the time if any.
N/A (No wallpaper)

**Additional context**
This is my second time trying to send this bug report. Sorry if I'm annoying!
I have installed all needed dependencies (EX: .NET desktop framework I think was one of them)

**Log file (Important)**
```2022-10-03 20:05:52.2108|INFO|Lively.App|
Lively v2.0.3.2 x64 desktop-native en-US
OS: Microsoft Windows 10 Pro 10.0.19044
CPU: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
CPU: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
GPU: NVIDIA GeForce GTX 680

2022-10-03 20:06:40.4098|INFO|Lively.App|AppUpdate status: uptodate
2022-10-03 20:06:40.4098|ERROR|Lively.RPC.AppUpdateServer|System.ObjectDisposedException: Cannot access a closed pipe.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.WriteTo(Stream stream)
   at GrpcDotNetNamedPipes.Internal.NamedPipeTransport.WriteTransaction.Commit()
   at GrpcDotNetNamedPipes.Internal.StreamWriterImpl`1.WriteAsync(T message)
   at GrpcDotNetNamedPipes.Internal.ResponseStreamWriterImpl`1.WriteAsync(T message)
   at Lively.RPC.AppUpdateServer.SubscribeUpdateChecked(Empty _, IServerStreamWriter`1 responseStream, ServerCallContext context) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\RPC\AppUpdateServer.cs:line 72
2022-10-03 20:10:20.7241|ERROR|Lively.Services.RunnerService|Failed to restore windowrect: WaitForInputIdle failed.  This could be because the process does not have a graphical interface.
2022-10-03 20:11:13.1059|ERROR|Lively.Services.RunnerService|Failed to restore windowrect: WaitForInputIdle failed.  This could be because the process does not have a graphical interface.
```
That's All I have. If you need anymore info logs wise ill be happy to send them over

**Comment by calinlmao** [comment]
I also have the same problem.Tried both the microsoft shop app and the one from the website.It did suddenly stop working.
I havent found any fix.

**Comment by rocksdanister** [comment]
Looks like I missed it my bad https://github.com/rocksdanister/lively/issues/1314

@silentstromv2 If you have any overlay software disable it: 
https://github.com/rocksdanister/lively/wiki/Common-Problems#lively-keeps-crashing-on-startperformance-overlay-visible

**Comment by knightryry** [comment]
All Good! Looks like the error logs changed though(i think).

**Comment by rocksdanister** [comment]
@knightryry Can you try latest version 2.0.4.0?

**Comment by knightryry** [comment]
Sure! Give me a little bit.

**Comment by knightryry** [comment]
Same Exact Error on 2.0.4.0.
```2022-10-10 17:56:47.4642|INFO|Lively.App|
Lively v2.0.4.0 x64 desktop-native en-US
OS: Microsoft Windows 10 Pro 10.0.19044
CPU: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
CPU: Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz
GPU: NVIDIA GeForce GTX 680

2022-10-10 17:57:39.3966|INFO|Lively.App|AppUpdate status: uptodate
2022-10-10 17:57:39.3966|ERROR|Lively.RPC.AppUpdateServer|System.ObjectDisposedException: Cannot access a closed pipe.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.WriteTo(Stream stream)
   at GrpcDotNetNamedPipes.Internal.NamedPipeTransport.WriteTransaction.Commit()
   at GrpcDotNetNamedPipes.Internal.StreamWriterImpl`1.WriteAsync(T message)
   at GrpcDotNetNamedPipes.Internal.ResponseStreamWriterImpl`1.WriteAsync(T message)
   at Lively.RPC.AppUpdateServer.SubscribeUpdateChecked(Empty _, IServerStreamWriter`1 responseStream, ServerCallContext context) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\RPC\AppUpdateServer.cs:line 79
```

**Comment by rocksdanister** [comment]
That error is because the UI program is crashing and ipc connection is not closing with the core, its not the cause of the crash itself.

**Comment by knightryry** [comment]
Also Rivatuner Statistics is NOT running and I'm running activated Windows pro.. just wanted to clarify!

**Comment by knightryry** [comment]
Reinstalling windows seemed to fix it. (Had to reinstall due to windows bricking itself.). I'm guessing one of the dependencies broke.
