### ISSUE TITLE
crash upon click settings icon or add wallpaper

### ISSUE THREAD

**Issue by v8f** [rocksdanister/lively#1448]
**Describe the bug**
There is a crash upon clicking the settings icon or button and there is also another crash when I try to add a wallpaper.

**To Reproduce**
1. Go to Lively wallpaper
2. Click on Settings or add wallpaper
3. Program crashes

**Expected behavior**
Expected to see the settings menu or the add wallpaper menu.

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/80642858/199589465-3cd33c90-e836-42c2-a188-836c681c4d24.png)
[20221102_155145.txt](https://github.com/rocksdanister/lively/files/9923736/20221102_155145.txt)

**Desktop (please complete the following information):**
 - OS: Windows 10 (Modified) 
![image](https://user-images.githubusercontent.com/80642858/199589829-078fdad2-3750-403c-b114-0194d628812d.png)
 - GPU: GTX 1660 Ti (NVIDIA)

**Additional context**
I checked log file, it says a file is missing even though it is there.

**Comment by rocksdanister** [comment]
That error is normal on first run, it just means settings files are not created yet.

Uninstall current Lively and try the beta:
https://github.com/rocksdanister/lively-beta/releases

and share the `logs` and `UI` folder from `C:\Users\<UserName>\AppData\Local\Lively Wallpaper`

**Comment by v8f** [comment]
LOGS: [20221102_162442.txt](https://github.com/rocksdanister/lively/files/9923909/20221102_162442.txt)
UI: [20221102_162443.txt](https://github.com/rocksdanister/lively/files/9923910/20221102_162443.txt)

**Comment by v8f** [comment]
I also installed the beta.
![image](https://user-images.githubusercontent.com/80642858/199595485-76097b4d-cdfd-457b-9ddd-3f13c7d1013c.png)

**Comment by rocksdanister** [comment]
Got the error for add wallpaper:
```
2022-11-02 16:24:45.5875|ERROR|Lively.UI.WinUI.App|Microsoft.UI.Xaml.Markup.XamlParseException: XAML parsing failed.
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.LoadComponent(IObjectReference _obj, Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Microsoft.UI.Xaml.Application.LoadComponent(Object component, Uri resourceLocator, ComponentResourceLocation componentResourceLocation)
   at Lively.UI.WinUI.Views.Pages.AddWallpaperView.InitializeComponent() in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.UI.WinUI\obj\x86\Release\net6.0-windows10.0.18362\win10-x86\Views\Pages\AddWallpaperView.g.i.cs:line 43
   at Lively.UI.WinUI.Views.Pages.AddWallpaperView..ctor(AddWallpaperViewModel vm) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.UI.WinUI\Views\Pages\AddWallpaperView.xaml.cs:line 37
   at Lively.UI.WinUI.MainWindow.AddWallpaperButton_Click(Object sender, RoutedEventArgs e) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.UI.WinUI\Views\MainWindow.xaml.cs:line 269
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext.<>c__DisplayClass2_0.<Post>b__0()
```

Now try making it crash by going to the settings page and share the UI log.

**Comment by v8f** [comment]
Alright, sorry for the late response btw

**Comment by v8f** [comment]
UI: [20221102_182922.txt](https://github.com/rocksdanister/lively/files/9924564/20221102_182922.txt)

**Comment by rocksdanister** [comment]
Settings error:
```
2022-11-02 18:29:24.5425|ERROR|Lively.UI.WinUI.App|System.IO.FileNotFoundException: The specified module could not be found. (0x8007007E)
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.MeasureOverride(IObjectReference _obj, Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Size availableSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.MeasureOverride(IObjectReference _obj, Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Size availableSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.MeasureOverride(IObjectReference _obj, Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Size availableSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)
--- End of stack trace from previous location ---
   at WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0(Int32 hr)
   at WinRT.ExceptionHelpers.ThrowExceptionForHR(Int32 hr)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverridesMethods.MeasureOverride(IObjectReference _obj, Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.MeasureOverride(Size availableSize)
   at Microsoft.UI.Xaml.FrameworkElement.Microsoft.UI.Xaml.IFrameworkElementOverrides.MeasureOverride(Size availableSize)
   at ABI.Microsoft.UI.Xaml.IFrameworkElementOverrides.Do_Abi_MeasureOverride_0(IntPtr thisPtr, Size availableSize, Size* result)
```
