### ISSUE TITLE
Failed to set window parent

### ISSUE THREAD

**Issue by joko7777** [rocksdanister/lively#1583]
After update wallpapers are no longer working for me.

Looking to get them working again

LOG

2023-02-22 09:26:06.8773|INFO|Lively.App|
Lively v2.0.6.0 x64 desktop-native en-US
OS: Microsoft Windows 10 Home 10.0.19044
CPU: AMD Ryzen 9 3900X 12-Core Processor
GPU: NVIDIA GeForce RTX 2080 SUPER

2023-02-22 09:26:18.4010|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: Rain | C:\Users\joshu\AppData\Local\Lively Wallpaper\Library\wallpapers\aahrtq0t.dme\index.html
2023-02-22 09:26:18.4519|INFO|Lively.Core.WinDesktopCore|Core initialized..
2023-02-22 09:26:18.4519|INFO|Lively.Core.Watchdog.WatchdogProcess|Starting watchdog service...
2023-02-22 09:26:18.7287|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef0: {"Type":0,"Hwnd":329186}
2023-02-22 09:26:19.5665|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=1920,Height=1080}
2023-02-22 09:26:19.5665|ERROR|Lively.Core.WinDesktopCore|System.Exception: Failed to set window parent.
   at Lively.Core.WinDesktopCore.SetParentWorkerW(IntPtr windowHandle) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Core\WinDesktopCore.cs:line 1090
   at Lively.Core.WinDesktopCore.SetWallpaperPerScreen(IntPtr handle, IDisplayMonitor targetDisplay) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Core\WinDesktopCore.cs:line 504
   at Lively.Core.WinDesktopCore.WallpaperInitialized(Object sender, WindowInitializedArgs e) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Core\WinDesktopCore.cs:line 344

**Comment by rocksdanister** [comment]
Update to latest: https://github.com/rocksdanister/lively/releases/tag/v2.0.6.1
