### ISSUE TITLE
Cannot Use Screensaver

### ISSUE THREAD

**Issue by Beeeeeast** [rocksdanister/lively#1584]
**Describe the bug**
The pop-up that says 'plugin required, one time setup is required to run screensaver' stays even after I download it

**To Reproduce**
1. Get lively from the Microsoft store
2. Go to active wallpapers
3. Go to screensaver
4. Download the screensaver file and follow the instructions
5. The pop up won't go away

**Expected behavior**
The pop up to go away after I download the screen saver

**Screenshots/Video**
![Lively Wallpaper 23_02_2023 6_46_10 AM](https://user-images.githubusercontent.com/126110900/220743267-ef3f015f-02e9-4173-8127-88e6e0fb59cc.png)
![Lively Wallpaper 23_02_2023 6_46_46 AM](https://user-images.githubusercontent.com/126110900/220743312-b8405965-9fc1-438a-aba8-2210779700bd.png)

**Desktop (please complete the following information):**
OS: Windows 11 Home

**Additional context**
I also tried deleting and redownloading it, and I tried to download the version not from the store, but nothing worked.

**Log file (Important)**
```
2023-02-23 06:09:47.2559|INFO|Lively.App|
Lively v2.0.6.0 x64 desktop-native en-GB
OS: Microsoft Windows 11 Home 10.0.22621
CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
GPU: Intel(R) Iris(R) Xe Graphics

2023-02-23 06:09:48.1563|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\jowan\AppData\Local\Lively Wallpaper\Settings.json'.
File name: 'C:\Users\jowan\AppData\Local\Lively Wallpaper\Settings.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.Common\Helpers\Storage\JsonStorage.cs:line 12
   at Lively.Services.JsonUserSettingsService.Load[T]() in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Services\JsonUserSettingsService.cs:line 109
2023-02-23 06:09:48.8223|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\jowan\AppData\Local\Lively Wallpaper\AppRules.json'.
File name: 'C:\Users\jowan\AppData\Local\Lively Wallpaper\AppRules.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.Common\Helpers\Storage\JsonStorage.cs:line 12
   at Lively.Services.JsonUserSettingsService.Load[T]() in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Services\JsonUserSettingsService.cs:line 123
2023-02-23 06:09:48.8521|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\jowan\AppData\Local\Lively Wallpaper\WallpaperLayout.json'.
File name: 'C:\Users\jowan\AppData\Local\Lively Wallpaper\WallpaperLayout.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.Common\Helpers\Storage\JsonStorage.cs:line 12
   at Lively.Services.JsonUserSettingsService.Load[T]() in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Services\JsonUserSettingsService.cs:line 140
2023-02-23 06:10:40.8884|INFO|Lively.App|AppUpdate status: available
2023-02-23 06:20:26.6586|INFO|Lively.App|
Lively v2.0.5.0 x64 desktop-bridge en-GB
OS: Microsoft Windows 11 Home 10.0.22621
CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
GPU: Intel(R) Iris(R) Xe Graphics

2023-02-23 06:20:28.2060|INFO|Lively.Helpers.WindowsStartup|Startup is disabled
2023-02-23 06:20:28.2426|INFO|Lively.Helpers.WindowsStartup|Request to enable startup Enabled
2023-02-23 06:22:07.3742|INFO|Lively.Services.ScreensaverService|Starting screensaver..
2023-02-23 06:22:07.3973|INFO|Lively.Services.ScreensaverService|Stopping screensaver..
2023-02-23 06:22:37.3819|INFO|Lively.Services.ScreensaverService|Starting screensaver..
2023-02-23 06:22:37.5647|INFO|Lively.Services.ScreensaverService|Stopping screensaver..
2023-02-23 06:24:34.3828|INFO|Lively.Services.ScreensaverService|Showing ss preview..
2023-02-23 06:24:34.4494|INFO|Lively.Core.WinDesktopCore|Display settings changed, screen(s):
2023-02-23 06:24:34.4494|INFO|Lively.Core.WinDesktopCore|\\.\DISPLAY1 {X=0,Y=0,Width=2880,Height=1920}
2023-02-23 06:24:41.7167|INFO|Lively.Services.ScreensaverService|Starting screensaver..
2023-02-23 06:24:43.8549|INFO|Lively.Services.ScreensaverService|Stopping screensaver..
2023-02-23 06:24:46.4703|INFO|Lively.Services.ScreensaverService|Starting screensaver..
2023-02-23 06:24:49.2447|INFO|Lively.Services.ScreensaverService|Stopping screensaver..
2023-02-23 06:26:26.7920|INFO|Lively.Services.TranslucentTBService|Taskbar theme: wallpaper
2023-02-23 06:26:26.7920|INFO|Lively.Services.TranslucentTBService|Taskbar theme service started.
2023-02-23 06:34:31.3341|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef0: {"Type":0,"Hwnd":1181266}
2023-02-23 06:34:31.6996|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef0: {"Type":2,"Success":true}
```

**Comment by rocksdanister** [comment]
That's normal, after its copied to `C:\Windows` and installed close and reopen the Active Wallpaper dialog - the popup should disappear.

**Comment by GoDjentle** [comment]
> That's normal, after its copied to `C:\Windows` and installed close and reopen the Active Wallpaper dialog - the popup should disappear.

What exactly do you mean by "close active wallpaper dialogue"?  I've ran into the same exact issue, troubleshooted and cannot get it to disappear. Is there not any code I can use to force remove the overlay on the screensaver menu in order to be able to change the settings?

**Comment by rocksdanister** [comment]
In the next update the overlay can be dismissed.
