### ISSUE TITLE
Open the software and flash back

### ISSUE THREAD

**Issue by FengLingXiao** [rocksdanister/lively#1821]
**Describe the bug**
When I tried to open the software, it crashed directly

**To Reproduce**
1. install software
2. open software
3. The screen flickers when it goes black
4. repeat or so

**Expected behavior**
I hope to open this software normally.

**Screenshots/Video**
https://github.com/rocksdanister/lively/assets/76095696/0d4da2eb-2101-4c19-91c2-c22a184c5e26

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 专业版 10.0.19045
-  I don't even have the software open

**Additional context**
I have used this software before. On the same device, I reinstalled the system and re-downloaded it, and it started to crash

**Log file (Important)**
```
2023-08-02 10:50:20.7574|INFO|Lively.App|
Lively v2.0.7.0 x64 desktop-native zh-CN
OS: Microsoft Windows 10 专业版 10.0.19045
CPU: AMD Ryzen 5 3600 6-Core Processor
GPU: NVIDIA GeForce GTX 1660 SUPER

2023-08-02 10:51:08.1480|INFO|Lively.App|AppUpdate status: uptodate
2023-08-02 10:51:08.1480|ERROR|Lively.RPC.AppUpdateServer|System.ObjectDisposedException: Cannot access a closed pipe.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.WriteTo(Stream stream)
   at GrpcDotNetNamedPipes.Internal.NamedPipeTransport.WriteTransaction.Commit()
   at GrpcDotNetNamedPipes.Internal.StreamWriterImpl`1.WriteAsync(T message)
   at GrpcDotNetNamedPipes.Internal.ResponseStreamWriterImpl`1.WriteAsync(T message)
   at Lively.RPC.AppUpdateServer.SubscribeUpdateChecked(Empty _, IServerStreamWriter`1 responseStream, ServerCallContext context) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\RPC\AppUpdateServer.cs:line 80
2023-08-02 10:51:08.1480|ERROR|Lively.RPC.AppUpdateServer|System.ObjectDisposedException: Cannot access a closed pipe.
   at System.IO.Pipes.PipeStream.CheckWriteOperations()
   at System.IO.Pipes.PipeStream.WriteAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.Pipes.PipeStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.WriteTo(Stream stream)
   at GrpcDotNetNamedPipes.Internal.NamedPipeTransport.WriteTransaction.Commit()
   at GrpcDotNetNamedPipes.Internal.StreamWriterImpl`1.WriteAsync(T message)
   at GrpcDotNetNamedPipes.Internal.ResponseStreamWriterImpl`1.WriteAsync(T message)
   at Lively.RPC.AppUpdateServer.SubscribeUpdateChecked(Empty _, IServerStreamWriter`1 responseStream, ServerCallContext context) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\RPC\AppUpdateServer.cs:line 80

```

**Comment by eavan02** [comment]
(This sentence was translated using a translator, so there may be some inaccuracies)
I am also experiencing a very similar bug. It occurs with both the Microsoft Store version and the installer version of the program. After the initial installation, the program worked correctly just once, but afterward, whether I completely exit the program or switch it to a background running state, a black screen appears and the program automatically shuts down when trying to execute it by any means. (However, the wallpaper is still applied normally, only the wallpaper selection UI does not open.) I tried resetting the program's data, and even uninstalling and reinstalling, but the same bug keeps occurring. Even right after reinstalling, it didn't open. When I restored Windows to the state it was in the day before installing the program, it opened again. But once again, it only opened once, and the same bug repeated thereafter.

The bug has certainly occurred, but there seems to be no problem at all in the logs.
```
2023-08-07 20:02:44.5798|INFO|Lively.App|
Lively v2.0.7.0 x64 desktop-native ko-KR
OS: Microsoft Windows 10 Pro 10.0.19045
CPU: AMD Ryzen 5 5600X 6-Core Processor
GPU: NVIDIA GeForce RTX 3060 Ti

2023-08-07 20:02:45.8945|INFO|Lively.Core.WinDesktopCore|Restoring wallpaper Periodic Table | C:\Users\study\AppData\Local\Lively Wallpaper\Library\wallpapers\ptpcxvcd.hlz
2023-08-07 20:02:45.8945|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: Periodic Table | C:\Users\study\AppData\Local\Lively Wallpaper\Library\wallpapers\ptpcxvcd.hlz\index.html
2023-08-07 20:02:45.9057|INFO|Lively.Core.WinDesktopCore|Core initialized..
2023-08-07 20:02:45.9057|INFO|Lively.Core.Watchdog.WatchdogProcess|Starting watchdog service...
2023-08-07 20:02:46.9466|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef0: {"Type":0,"Hwnd":1377672}
2023-08-07 20:02:47.0062|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=-1920,Y=0,Width=1920,Height=1080}
2023-08-07 20:02:47.0290|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 13264
2023-08-07 20:02:47.2346|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef0: {"Type":2,"Success":true}
```
