### ISSUE TITLE
Fluid v2 wallpaper not working.

### ISSUE THREAD

**Issue by F3L1X05** [rocksdanister/lively#185]
Every wallpaper is working except the wallpaper Fluids v2. I dont know what to do there is an error every time i change it to Fluid v2 So here is my Log:

2020-11-04 22:01:37.2185|INFO|livelywpf.NLogger|
Lively v1.1.2.0 de-DE 64Bit:False MSIX:False
OS: Microsoft Windows 10 Pro 10.0.19041
CPU: AMD Ryzen 5 3600 6-Core Processor              
GPU: NVIDIA GeForce RTX 2060 SUPER

2020-11-04 22:01:37.6290|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\felix\AppData\Local\Lively Wallpaper\Library\wallpapers\0wj1biqk.f41\fluid.html webaudio
2020-11-04 22:01:37.6316|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\felix\AppData\Local\Lively Wallpaper\Library\wallpapers\aahrtq0t.dme\index.html web
2020-11-04 22:01:37.6316|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\felix\AppData\Local\Lively Wallpaper\Library\wallpapers\gdkyowfb.3tk\eternal_light_version2.mp4 video
2020-11-04 22:01:37.6316|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\felix\AppData\Local\Lively Wallpaper\Library\wallpapers\iqdvd4pt.jyo\triangle.html web
2020-11-04 22:01:37.6316|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\felix\AppData\Local\Lively Wallpaper\Library\wallpapers\lgz4xpht.sjn\index.html web
2020-11-04 22:01:37.6316|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\felix\AppData\Local\Lively Wallpaper\Library\wallpapers\mrn3a0m5.0lk\index.html web
2020-11-04 22:01:37.6316|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\felix\AppData\Local\Lively Wallpaper\Library\wallpapers\nps35xrp.5eh\jellyfish.html web
2020-11-04 22:01:37.6316|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\felix\AppData\Local\Lively Wallpaper\Library\wallpapers\ptpcxvcd.hlz\index.html web
2020-11-04 22:01:37.6316|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\felix\AppData\Local\Lively Wallpaper\Library\wallpapers\rtnm43pj.wyl\index.html web
2020-11-04 22:01:37.6316|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\felix\AppData\Local\Lively Wallpaper\Library\wallpapers\v44be4yd.a1r\ribbon.html web
2020-11-04 22:01:37.6316|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\felix\AppData\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2\index.html web
2020-11-04 22:01:37.6316|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\felix\AppData\Local\Lively Wallpaper\Library\wallpapers\zddkyl1e.gkl\starfield.html web
2020-11-04 22:01:38.7773|ERROR|livelywpf.WallpaperLayoutJSON|System.IO.FileNotFoundException: Could not find file 'C:\Users\felix\AppData\Local\Lively Wallpaper\WallpaperLayout.json'.
File name: 'C:\Users\felix\AppData\Local\Lively Wallpaper\WallpaperLayout.json'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at livelywpf.WallpaperLayoutJSON.LoadWallpaperLayout(String filePath) in C:\Users\rocks\source\repos\livelywpf\livelywpf\DataJSON\WallpaperLayoutJSON.cs:line 49
2020-11-04 22:02:19.9267|INFO|livelywpf.SetupDesktop|Core: Setting Wallpaper=>Fluids v2
2020-11-04 22:02:19.9294|INFO|livelywpf.SetupDesktop|Core Initialized
2020-11-04 22:02:22.4863|ERROR|livelywpf.SetupDesktop|Core: Failed to launch wallpaper=>Process exited before giving HWND.
System.Exception: Oops... Looks like something went wrong :(
In order to better understand this error and fix the issue, share the log file with the developer.
Instructions for sharing log file:
https://github.com/rocksdanister/lively/wiki
2020-11-04 22:02:35.5157|INFO|livelywpf.SetupDesktop|Core: Setting Wallpaper=>Fluids v2
2020-11-04 22:02:38.0699|ERROR|livelywpf.SetupDesktop|Core: Failed to launch wallpaper=>Process exited before giving HWND.
System.Exception: Oops... Looks like something went wrong :(
In order to better understand this error and fix the issue, share the log file with the developer.
Instructions for sharing log file:
https://github.com/rocksdanister/lively/wiki
2020-11-04 22:10:55.4675|INFO|livelywpf.Core.Playback|Getting processname failure/handle null, resuming playback!

Hope you can help me (;

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/153
