### ISSUE TITLE
Wallpaper gets overdrawn by windows native wallpaper fade transition

### ISSUE THREAD

**Issue by shubhz04** [rocksdanister/lively#2162]
So whenever a slideshow happens in background , it kinds of fades in a new image for a sec and then goes back. is there any way to stop it? 

heres a video to see, check @00:14 seconds after that
https://youtu.be/h4yphZAKtxs

```
[LOGS]
2024-03-16 14:30:21.8368|INFO|Lively.App|
Lively v2.0.7.4 x64 desktop-bridge en-GB
OS: Microsoft Windows 11 Pro 10.0.22631
CPU: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
GPU: Intel(R) UHD Graphics 620
GPU: NVIDIA GeForce MX150

2024-03-16 14:30:22.1346|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\shubhz\AppData\Local\Lively Wallpaper\Settings.json'.
File name: 'C:\Users\shubhz\AppData\Local\Lively Wallpaper\Settings.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath)
   at Lively.Services.JsonUserSettingsService.Load[T]()
2024-03-16 14:30:22.5897|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\shubhz\AppData\Local\Lively Wallpaper\AppRules.json'.
File name: 'C:\Users\shubhz\AppData\Local\Lively Wallpaper\AppRules.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath)
   at Lively.Services.JsonUserSettingsService.Load[T]()
2024-03-16 14:30:22.6269|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\shubhz\AppData\Local\Lively Wallpaper\WallpaperLayout.json'.
File name: 'C:\Users\shubhz\AppData\Local\Lively Wallpaper\WallpaperLayout.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath)
   at Lively.Services.JsonUserSettingsService.Load[T]()
2024-03-16 14:30:23.1549|INFO|Lively.Helpers.WindowsStartup|Startup is disabled
2024-03-16 14:30:23.2615|INFO|Lively.Helpers.WindowsStartup|Request to enable startup Enabled
2024-03-16 14:30:23.3115|INFO|Lively.Core.WinDesktopCore|WorkerW initializing..
2024-03-16 14:30:23.4446|INFO|Lively.Core.WinDesktopCore|WorkerW initialized 65878
2024-03-16 14:30:23.4446|INFO|Lively.Core.WinDesktopCore|Hooking WorkerW events..
2024-03-16 14:30:25.9900|INFO|Lively.Views.WindowMsg.RawInputMsgWindow|Desktop handles updated.
2024-03-16 14:30:25.9970|INFO|Lively.Core.Suspend.Playback|Desktop handles updated.
2024-03-16 14:31:23.7580|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: Rain | C:\Users\shubhz\AppData\Local\Lively Wallpaper\Library\wallpapers\abqqpcp4.hv3\index.html
2024-03-16 14:31:23.7580|INFO|Lively.Core.Watchdog.WatchdogProcess|Starting watchdog service...
2024-03-16 14:31:26.9819|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef0: {"Type":0,"Hwnd":132900}
2024-03-16 14:31:27.1426|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=1366,Height=768}
2024-03-16 14:31:27.3784|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 15188
2024-03-16 14:31:29.0756|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef0: {"Type":2,"Success":true}
```

**Comment by rocksdanister** [comment]
If you are using newer version of Windows then unchecking "Animate controls and elements inside windows" should remove the transition effect.

Basically the opposite of whats instructed here:
https://github.com/rocksdanister/lively/wiki/Getting-Started#windows-settings-optional

Alternatively, just turn off Windows slideshow since Lively is managing the wallpaper right now?
