### ISSUE TITLE
The program keep showing black screen and not responding.

### ISSUE THREAD

**Issue by LuPow132** [rocksdanister/lively#2187]
**Describe the bug**
When open the Lively Wallpaper app, The program keep showing black screen and not responding.

**To Reproduce**
1.Just right click and open program
2.That's it

**Expected behavior**
Beable to enter the program

**Screenshots/Video**
![image](https://github.com/rocksdanister/lively/assets/68886157/d5dbb36e-8da8-497a-8255-19cad60de3ab)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 23H2

**Log file (Important)**
```
2024-04-09 17:55:35.6719|INFO|Lively.App|
Lively v2.0.7.4 x64 desktop-native en-US
OS: Microsoft Windows 11 Pro 10.0.22631
CPU: Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
GPU: Intel(R) UHD Graphics 630
GPU: NVIDIA GeForce GTX 1050 Ti

2024-04-09 17:55:35.7928|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\Acer\AppData\Local\Lively Wallpaper\Settings.json'.
File name: 'C:\Users\Acer\AppData\Local\Lively Wallpaper\Settings.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.Common\Helpers\Storage\JsonStorage.cs:line 12
   at Lively.Services.JsonUserSettingsService.Load[T]() in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Services\JsonUserSettingsService.cs:line 109
2024-04-09 17:55:35.9265|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\Acer\AppData\Local\Lively Wallpaper\AppRules.json'.
File name: 'C:\Users\Acer\AppData\Local\Lively Wallpaper\AppRules.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.Common\Helpers\Storage\JsonStorage.cs:line 12
   at Lively.Services.JsonUserSettingsService.Load[T]() in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Services\JsonUserSettingsService.cs:line 123
2024-04-09 17:55:35.9387|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\Acer\AppData\Local\Lively Wallpaper\WallpaperLayout.json'.
File name: 'C:\Users\Acer\AppData\Local\Lively Wallpaper\WallpaperLayout.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.Common\Helpers\Storage\JsonStorage.cs:line 12
   at Lively.Services.JsonUserSettingsService.Load[T]() in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Services\JsonUserSettingsService.cs:line 140
2024-04-09 17:55:35.9660|INFO|Lively.Core.WinDesktopCore|WorkerW initializing..
2024-04-09 17:55:36.0075|INFO|Lively.Core.WinDesktopCore|WorkerW initialized 2689504
2024-04-09 17:55:36.0075|INFO|Lively.Core.WinDesktopCore|Hooking WorkerW events..
2024-04-09 17:55:36.3232|INFO|Lively.Views.WindowMsg.RawInputMsgWindow|Desktop handles updated.
2024-04-09 17:55:36.3232|INFO|Lively.Core.Suspend.Playback|Desktop handles updated.
2024-04-09 17:56:24.4608|INFO|Lively.App|AppUpdate status: uptodate


```

**Comment by LuPow132** [comment]
Somehow chaging regieon from Thai to English(US) fixed it????

**Comment by rocksdanister** [comment]
Interesting, does it still turn to black if u switch region back to Thai?

**Comment by LuPow132** [comment]
Yes when I change region back to Thai it start to turn black again
Img of when I change region to Thai
![image](https://github.com/rocksdanister/lively/assets/68886157/435a228a-5607-437d-ba6f-343b9d94110d)

Img of when I change back to English(US)
![image](https://github.com/rocksdanister/lively/assets/68886157/83d70916-2372-4eeb-8a3a-1857478498e6)

**Comment by rocksdanister** [comment]
Can you check if this problem also happens with [Powertoys](https://github.com/microsoft/PowerToys) (another WinUI 3 app.)

The UI logs are in `C:\Users\Acer\AppData\Local\Lively Wallpaper\UI`

**Comment by LuPow132** [comment]
Here is the log
```
2024-04-11 17:14:30.6162|INFO|Lively.UI.WinUI.ViewModels.LibraryViewModel|Loaded wallpaper: C:\Users\Acer\AppData\Local\Lively Wallpaper\Library\wallpapers\0wj1biqk.f41\fluid.html
2024-04-11 17:14:30.6675|INFO|Lively.UI.WinUI.ViewModels.LibraryViewModel|Loaded wallpaper: C:\Users\Acer\AppData\Local\Lively Wallpaper\Library\wallpapers\4yvhquwl.pcv\index.html
2024-04-11 17:14:30.6675|INFO|Lively.UI.WinUI.ViewModels.LibraryViewModel|Loaded wallpaper: C:\Users\Acer\AppData\Local\Lively Wallpaper\Library\wallpapers\abqqpcp4.hv3\index.html
2024-04-11 17:14:30.6675|INFO|Lively.UI.WinUI.ViewModels.LibraryViewModel|Loaded wallpaper: C:\Users\Acer\AppData\Local\Lively Wallpaper\Library\wallpapers\iqdvd4pt.jyo\triangle.html
2024-04-11 17:14:30.6675|INFO|Lively.UI.WinUI.ViewModels.LibraryViewModel|Loaded wallpaper: C:\Users\Acer\AppData\Local\Lively Wallpaper\Library\wallpapers\lgz4xpht.sjn\index.html
2024-04-11 17:14:30.6759|INFO|Lively.UI.WinUI.ViewModels.LibraryViewModel|Loaded wallpaper: C:\Users\Acer\AppData\Local\Lively Wallpaper\Library\wallpapers\mylulkt4.dn1\index.html
2024-04-11 17:14:30.6759|INFO|Lively.UI.WinUI.ViewModels.LibraryViewModel|Loaded wallpaper: C:\Users\Acer\AppData\Local\Lively Wallpaper\Library\wallpapers\nps35xrp.5eh\jellyfish.html
2024-04-11 17:14:30.6759|INFO|Lively.UI.WinUI.ViewModels.LibraryViewModel|Loaded wallpaper: C:\Users\Acer\AppData\Local\Lively Wallpaper\Library\wallpapers\ptpcxvcd.hlz\index.html
2024-04-11 17:14:30.6759|INFO|Lively.UI.WinUI.ViewModels.LibraryViewModel|Loaded wallpaper: C:\Users\Acer\AppData\Local\Lively Wallpaper\Library\wallpapers\rtnm43pj.wyl\index.html
2024-04-11 17:14:30.6759|INFO|Lively.UI.WinUI.ViewModels.LibraryViewModel|Loaded wallpaper: C:\Users\Acer\AppData\Local\Lively Wallpaper\Library\wallpapers\wxqfmbno.3vk\index.html
2024-04-11 17:14:30.6759|INFO|Lively.UI.WinUI.ViewModels.LibraryViewModel|Loaded wallpaper: C:\Users\Acer\AppData\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2\index.html
2024-04-11 17:14:30.6759|INFO|Lively.UI.WinUI.ViewModels.LibraryViewModel|Loaded wallpaper: C:\Users\Acer\AppData\Local\Lively Wallpaper\Library\wallpapers\zmijuhra.1n3\index.html
2024-04-11 17:14:30.6759|INFO|Lively.UI.WinUI.ViewModels.LibraryViewModel|Loaded wallpaper: D:\Wallpaper\Black Hole from Interstellar Wallpaper In 4K  Live Wallpaper.mp4
2024-04-11 17:14:31.1772|INFO|Lively.UI.WinUI.MainWindow|Skipping login: Token not found.
```

**Comment by rocksdanister** [comment]
Can you try building and running the latest UI project from this repo.

Otherwise I can try sharing it via email if you message me.

**Comment by WilsonBae** [comment]
I changed Region to US, but still there is a problem. UI is not working. 
[20240430_144835.txt](https://github.com/rocksdanister/lively/files/15158786/20240430_144835.txt)
Here is the log from UI folder.
[20240430_144832.txt](https://github.com/rocksdanister/lively/files/15158797/20240430_144832.txt)
And this is the log file.

Powertoy3 has same issue.

**Comment by rocksdanister** [comment]
Can you try to reproduce the issue in beta build:
https://github.com/rocksdanister/lively-beta/releases/tag/v2.1.0.1

**Comment by WilsonBae** [comment]
Still does not work on my PC.
[image: image.png]

Check the log file

2024년 5월 17일 (금) 오전 2:43, Dani John ***@***.***>님이 작성:
