### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by dickdanger85** [rocksdanister/lively#232]
Has anyone been having an issue with the LivelyWallpaper crashing and not being able to bring it back? Its been fine for two weeks when I downloaded it, but yesterday it started displaying a black screen and you couldn't open the menu from the tray with a right click or anything. In order to get it working again, I have to restart the computer. Other times it just turned off and I had my default wallpaper, as if the application had been closed. At these times, you could just reopen it and start over.  Just curious if its a setting on my computer or an issue in the program. 

**Desktop:**
 - OS: Windows 10
- Which wallpaper was running at the time if any: One was a "holidays are coming" one with the floating coca cola cars and some music. The other times it was the tower block game.

**Additional context**

**Log file**
[20201209_031542.txt](https://github.com/rocksdanister/lively/files/5683209/20201209_031542.txt)
[20201212_021010.txt](https://github.com/rocksdanister/lively/files/5683211/20201212_021010.txt)
[20201212_021207.txt](https://github.com/rocksdanister/lively/files/5683212/20201212_021207.txt)
[20201212_033806.txt](https://github.com/rocksdanister/lively/files/5683213/20201212_033806.txt)

**Comment by rocksdanister** [comment]
Only one of the logfile has record of crash:
```cs
2020-12-12 03:37:28.5983|ERROR|livelywpf.App|Unhandled exception in livelywpf v1.1.6.0
System.ComponentModel.Win32Exception (1158): Error creating window handle.
   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Application.ParkHandle(CreateParams cp, DpiAwarenessContext dpiAwarenessContext)
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t)
   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)
   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.OnThreadException(Exception e)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
Looks like a leak to me, have to look into it.

**Comment by dickdanger85** [comment]
Honestly, when I went in to the log files, I was surprised to only see 5 of them. One from two weeks ago, and the four I sent. I changed the settings to not pause when a window is open to see if it helps at all. It hasn’t crashed, but maybe im looking in the wrong place.  Sent from Mail for Windows 10 From: Dani JohnSent: Saturday, December 12, 2020 10:56 PMTo: rocksdanister/livelyCc: dickdanger85; AuthorSubject: Re: [rocksdanister/lively] Troubleshooting (#232) Only one of the logfile has record of crash:2020-12-12 03:37:28.5983|ERROR|livelywpf.App|Unhandled exception in livelywpf v1.1.6.0System.ComponentModel.Win32Exception (1158): Error creating window handle.   at System.Windows.Forms.NativeWindow.CreateHandle(CreateParams cp)   at System.Windows.Forms.Control.CreateHandle()   at System.Windows.Forms.Control.get_Handle()   at System.Windows.Forms.Application.ParkHandle(CreateParams cp, DpiAwarenessContext dpiAwarenessContext)   at System.Windows.Forms.Control.CreateHandle()   at System.Windows.Forms.Control.get_Handle()   at System.Windows.Forms.ThreadExceptionDialog..ctor(Exception t)   at System.Windows.Forms.Application.ThreadContext.OnThreadException(Exception t)   at System.Windows.Forms.NotifyIcon.NotifyIconNativeWindow.OnThreadException(Exception e)   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)Looks like a leak to me, have to look into it.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by rocksdanister** [comment]
Please don't reply by mail, its messing up the message format.
> I was surprised to only see 5 of them.

Lively keeps last 5 logfile copy regardless of error.
>I changed the settings to not pause when a window is open to see if it helps at all.

Yes I have a clue what's happening, will look into it.

**Comment by dickdanger85** [comment]
sorry about that. it was a reflex while doing work emails

**Comment by rocksdanister** [comment]
Can you try the beta build with wallpaper pause enabled:
https://github.com/rocksdanister/lively-beta/releases
