### ISSUE TITLE
Hi when i try to change my screensaver it will always come up with plugin required when i have followed the steps and everything copying it into Windows (C:) and then installing it but the pop up still will not go away. Any help would be appreciated. 

### ISSUE THREAD

**Issue by Myst-24** [rocksdanister/lively#2352]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10 1909]
- Which wallpaper was running at the time if any.

**Additional context**

**Log file (Important)**
Share the diagnostic files by:
Open Lively settings (Gear icon) top-right -> System -> Log File -> Save
or 
Navigate to Appdata folder `C:\Users\<UserName>\AppData\Local\Lively Wallpaper\logs`

**Comment by Myst-24** [comment]
2024-08-09 01:29:06.7108|INFO|Lively.App|
Lively v2.1.0.8 x64 desktop-native en-GB
OS: Microsoft Windows 11 Home 10.0.22631
CPU: AMD Ryzen 7 5800H with Radeon Graphics
GPU: NVIDIA GeForce RTX 3060 Laptop GPU
GPU: AMD Radeon(TM) Graphics

2024-08-09 01:29:06.9497|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\mysto\AppData\Local\Lively Wallpaper\Settings.json'.
File name: 'C:\Users\mysto\AppData\Local\Lively Wallpaper\Settings.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.Common\Helpers\Storage\JsonStorage.cs:line 12
   at Lively.Services.JsonUserSettingsService.Load[T]() in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Services\JsonUserSettingsService.cs:line 120
2024-08-09 01:29:07.1615|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\mysto\AppData\Local\Lively Wallpaper\AppRules.json'.
File name: 'C:\Users\mysto\AppData\Local\Lively Wallpaper\AppRules.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.Common\Helpers\Storage\JsonStorage.cs:line 12
   at Lively.Services.JsonUserSettingsService.Load[T]() in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Services\JsonUserSettingsService.cs:line 134
2024-08-09 01:29:07.1696|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\mysto\AppData\Local\Lively Wallpaper\WallpaperLayout.json'.
File name: 'C:\Users\mysto\AppData\Local\Lively Wallpaper\WallpaperLayout.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath) in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively.Common\Helpers\Storage\JsonStorage.cs:line 12
   at Lively.Services.JsonUserSettingsService.Load[T]() in C:\Users\rocks\Documents\GitHub\lively\src\Lively\Lively\Services\JsonUserSettingsService.cs:line 151
2024-08-09 01:29:07.2082|INFO|Lively.Core.WinDesktopCore|WorkerW initializing..
2024-08-09 01:29:07.2670|INFO|Lively.Core.WinDesktopCore|WorkerW initialized 66758
2024-08-09 01:29:07.2670|INFO|Lively.Core.WinDesktopCore|Hooking WorkerW events..
2024-08-09 01:29:07.5279|INFO|Lively.Views.WindowMsg.RawInputMsgWindow|Desktop handles updated.
2024-08-09 01:29:07.5279|INFO|Lively.Core.Suspend.Playback|Desktop handles updated.
2024-08-09 01:29:16.7489|INFO|Lively.App|AppUpdate status: uptodate
2024-08-09 01:29:23.2764|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: Fairy Tail - Opening 1 (Creditless) (HD - 60 fps) | C:\Users\mysto\OneDrive\Documents\Fairy Tail - Opening 1 (Creditless) (HD - 60 fps).wmv
2024-08-09 01:29:23.2764|INFO|Lively.Core.Watchdog.WatchdogProcess|Starting watchdog service...
2024-08-09 01:29:23.6820|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0:  (+) Video --vid=1 (msmpeg4v3 1920x1080 59.940fps)
2024-08-09 01:29:23.6820|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0:  (+) Audio --aid=1 --alang=eng (wmav2 2ch 44100Hz)
2024-08-09 01:29:24.4604|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0: AO: [wasapi] 48000Hz stereo 2ch float
2024-08-09 01:29:24.4639|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0: VO: [gpu] 1920x1080 yuv420p
2024-08-09 01:29:34.7979|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=2560,Height=1440}
2024-08-09 01:29:34.8237|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 5444
2024-08-09 01:29:40.6311|INFO|Lively.App|AppUpdate status: uptodate
2024-08-09 01:29:46.3003|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: Naruto Shippuden Opening 16   4K   60 FPS | C:\Users\mysto\Downloads\Naruto Shippuden Opening 16   4K   60 FPS.mp4
2024-08-09 01:29:46.3712|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv1:  (+) Video --vid=1 (*) (h264 1920x1080 28.687fps)
2024-08-09 01:29:46.3712|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv1:  (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
2024-08-09 01:29:46.5550|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv1: Using hardware decoding (d3d11va).
2024-08-09 01:29:46.9088|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv1: AO: [wasapi] 48000Hz stereo 2ch float
2024-08-09 01:29:46.9088|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv1: VO: [gpu] 1920x1080 d3d11[nv12]
2024-08-09 01:29:56.6536|INFO|Lively.Core.Watchdog.WatchdogProcess|Removing program to watchdog: 5444
2024-08-09 01:29:56.6536|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=2560,Height=1440}
2024-08-09 01:29:56.6860|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 23468
2024-08-09 01:30:55.9490|INFO|Lively.Services.ScreensaverService|Showing ss preview..
2024-08-09 01:30:56.0945|INFO|Lively.Core.WinDesktopCore|Display settings changed, screen(s):
2024-08-09 01:30:56.0945|INFO|Lively.Core.WinDesktopCore|\\.\DISPLAY1 {X=0,Y=0,Width=2560,Height=1440}
2024-08-09 01:30:56.0945|INFO|Lively.Core.WinDesktopCore|Updating wallpaper rect(Screen): {X=0,Y=0,Width=2560,Height=1440} -> {X=0,Y=0,Width=2560,Height=1440}.
2024-08-09 01:31:00.9746|INFO|Lively.Services.ScreensaverService|Showing ss preview..
2024-08-09 01:31:01.1104|INFO|Lively.Core.WinDesktopCore|Display settings changed, screen(s):
2024-08-09 01:31:01.1104|INFO|Lively.Core.WinDesktopCore|\\.\DISPLAY1 {X=0,Y=0,Width=2560,Height=1440}
2024-08-09 01:31:01.1104|INFO|Lively.Core.WinDesktopCore|Updating wallpaper rect(Screen): {X=0,Y=0,Width=2560,Height=1440} -> {X=0,Y=0,Width=2560,Height=1440}.
2024-08-09 01:31:03.0003|INFO|Lively.Services.ScreensaverService|Showing ss preview..
2024-08-09 01:31:03.1382|INFO|Lively.Core.WinDesktopCore|Display settings changed, screen(s):
2024-08-09 01:31:03.1382|INFO|Lively.Core.WinDesktopCore|\\.\DISPLAY1 {X=0,Y=0,Width=2560,Height=1440}
2024-08-09 01:31:03.1382|INFO|Lively.Core.WinDesktopCore|Updating wallpaper rect(Screen): {X=0,Y=0,Width=2560,Height=1440} -> {X=0,Y=0,Width=2560,Height=1440}.
2024-08-09 01:31:28.6119|INFO|Lively.Services.ScreensaverService|Starting screensaver..
2024-08-09 01:31:28.6119|INFO|Lively.Services.ScreensaverService|Starting screensaver Naruto Shippuden Opening 16   4K   60 FPS | C:\Users\mysto\AppData\Local\Lively Wallpaper\Library\SaveData\wptmp\v1ikkygd.rxv | {X=0,Y=0,Width=2560,Height=1440}
2024-08-09 01:31:28.7953|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv2:  (+) Video --vid=1 (*) (h264 1920x1080 28.687fps)
2024-08-09 01:31:28.7953|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv2:  (+) Audio --aid=1 (*) (aac 2ch 44100Hz)
2024-08-09 01:31:28.9548|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv2: Using hardware decoding (d3d11va).
2024-08-09 01:31:29.2656|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv2: AO: [wasapi] 48000Hz stereo 2ch float
2024-08-09 01:31:29.2656|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv2: VO: [gpu] 1920x1080 d3d11[nv12]
2024-08-09 01:31:31.2646|INFO|Lively.Services.ScreensaverService|Stopping screensaver..
2024-08-09 01:31:31.2646|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv2: [input] No key binding found for key 'SPACE'.
2024-08-09 01:31:48.7068|INFO|Lively.Core.Watchdog.WatchdogProcess|Cleared watchdog program(s)..
