### ISSUE TITLE
WorkerW destroyed

### ISSUE THREAD

**Issue by cartujito** [rocksdanister/lively#2407]
2024-09-28 01:08:09.7896|INFO|Lively.App|
Lively v2.1.0.9 x64 desktop-bridge es-ES
OS: Microsoft Windows 11 Pro 10.0.26100
CPU: 11th Gen Intel(R) Core(TM) i5-11400 @ 2.60GHz
GPU: AMD Radeon RX 6400

2024-09-28 01:08:09.8512|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\Oscar\AppData\Local\Lively Wallpaper\Settings.json'.
File name: 'C:\Users\Oscar\AppData\Local\Lively Wallpaper\Settings.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath)
   at Lively.Services.JsonUserSettingsService.Load[T]()
2024-09-28 01:08:09.9300|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\Oscar\AppData\Local\Lively Wallpaper\AppRules.json'.
File name: 'C:\Users\Oscar\AppData\Local\Lively Wallpaper\AppRules.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath)
   at Lively.Services.JsonUserSettingsService.Load[T]()
2024-09-28 01:08:09.9300|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\Oscar\AppData\Local\Lively Wallpaper\WallpaperLayout.json'.
File name: 'C:\Users\Oscar\AppData\Local\Lively Wallpaper\WallpaperLayout.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath)
   at Lively.Services.JsonUserSettingsService.Load[T]()
2024-09-28 01:08:10.0121|INFO|Lively.Helpers.WindowsStartup|Startup is disabled
2024-09-28 01:08:10.0245|INFO|Lively.Helpers.WindowsStartup|Request to enable startup Enabled
2024-09-28 01:08:10.0245|WARN|Lively.Services.RunnerService|Process is running elevated, UI may not function properly.
2024-09-28 01:08:10.0245|INFO|Lively.Core.WinDesktopCore|WorkerW initializing..
2024-09-28 01:08:10.0245|INFO|Lively.Core.WinDesktopCore|WorkerW initialized 8978784
2024-09-28 01:08:10.0245|INFO|Lively.Core.WinDesktopCore|Hooking WorkerW events..
2024-09-28 01:08:10.1407|INFO|Lively.Views.WindowMsg.RawInputMsgWindow|Desktop handles updated.
2024-09-28 01:08:10.1407|INFO|Lively.Core.Suspend.Playback|Desktop handles updated.
2024-09-28 01:08:20.6432|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: Music Tunnel | C:\Users\Oscar\AppData\Local\Lively Wallpaper\Library\wallpapers\spfaevge.qza\index.html
2024-09-28 01:08:20.6432|INFO|Lively.Core.Watchdog.WatchdogProcess|Starting watchdog service...
2024-09-28 01:08:21.1079|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef0: {"Type":0,"Hwnd":4851356}
2024-09-28 01:08:21.1275|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=1920,Height=1080}
2024-09-28 01:08:21.1475|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 16380
2024-09-28 01:08:22.2595|ERROR|Lively.Core.WinDesktopCore|WorkerW destroyed.
2024-09-28 01:08:22.2595|INFO|Lively.Core.WinDesktopCore|Restarting wallpaper service..
2024-09-28 01:08:22.2595|INFO|Lively.Core.Watchdog.WatchdogProcess|Cleared watchdog program(s)..
2024-09-28 01:08:22.2595|INFO|Lively.Core.WinDesktopCore|WorkerW initializing..
2024-09-28 01:08:22.2722|INFO|Lively.Core.WinDesktopCore|WorkerW initialized 5112788
2024-09-28 01:08:22.2722|INFO|Lively.Views.WindowMsg.RawInputMsgWindow|Desktop handles updated.
2024-09-28 01:08:22.2722|INFO|Lively.Core.Suspend.Playback|Desktop handles updated.
2024-09-28 01:08:22.2722|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: Music Tunnel | C:\Users\Oscar\AppData\Local\Lively Wallpaper\Library\wallpapers\spfaevge.qza\index.html
2024-09-28 01:08:22.8009|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef1: {"Type":0,"Hwnd":2425642}
2024-09-28 01:08:22.8208|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=1920,Height=1080}
2024-09-28 01:08:22.8392|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 15700
2024-09-28 01:08:23.0846|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef1: {"Type":2,"Success":true}
2024-09-28 01:08:23.4107|ERROR|Lively.Core.WinDesktopCore|WorkerW destroyed.
2024-09-28 01:08:23.4107|INFO|Lively.Core.WinDesktopCore|Restarting wallpaper service..
2024-09-28 01:08:23.4107|INFO|Lively.Core.Watchdog.WatchdogProcess|Cleared watchdog program(s)..
2024-09-28 01:08:23.4107|INFO|Lively.Core.WinDesktopCore|WorkerW initializing..
2024-09-28 01:08:23.4107|INFO|Lively.Core.WinDesktopCore|WorkerW initialized 2687916
2024-09-28 01:08:23.4107|INFO|Lively.Views.WindowMsg.RawInputMsgWindow|Desktop handles updated.
2024-09-28 01:08:23.4107|INFO|Lively.Core.Suspend.Playback|Desktop handles updated.
2024-09-28 01:08:23.4107|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: Music Tunnel | C:\Users\Oscar\AppData\Local\Lively Wallpaper\Library\wallpapers\spfaevge.qza\index.html
2024-09-28 01:08:23.8838|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef2: {"Type":0,"Hwnd":4982218}
2024-09-28 01:08:23.9081|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=1920,Height=1080}
2024-09-28 01:08:23.9272|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 19328
2024-09-28 01:08:24.1343|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef2: {"Type":2,"Success":true}
2024-09-28 01:08:24.5513|ERROR|Lively.Core.WinDesktopCore|WorkerW destroyed.
2024-09-28 01:08:24.5513|INFO|Lively.Core.WinDesktopCore|Restarting wallpaper service..
2024-09-28 01:08:24.5513|INFO|Lively.Core.Watchdog.WatchdogProcess|Cleared watchdog program(s)..
2024-09-28 01:08:24.5513|INFO|Lively.Core.WinDesktopCore|WorkerW initializing..
2024-09-28 01:08:24.5513|INFO|Lively.Core.WinDesktopCore|WorkerW initialized 37618802
2024-09-28 01:08:24.5513|INFO|Lively.Views.WindowMsg.RawInputMsgWindow|Desktop handles updated.
2024-09-28 01:08:24.5513|INFO|Lively.Core.Suspend.Playback|Desktop handles updated.
2024-09-28 01:08:24.5513|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: Music Tunnel | C:\Users\Oscar\AppData\Local\Lively Wallpaper\Library\wallpapers\spfaevge.qza\index.html
2024-09-28 01:08:25.0249|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef3: {"Type":0,"Hwnd":2623114}
2024-09-28 01:08:25.0493|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=1920,Height=1080}
2024-09-28 01:08:25.0693|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 18320
2024-09-28 01:08:25.2962|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef3: {"Type":2,"Success":true}
2024-09-28 01:08:25.6919|ERROR|Lively.Core.WinDesktopCore|WorkerW destroyed.
2024-09-28 01:08:25.6919|INFO|Lively.Core.WinDesktopCore|Restarting wallpaper service..
2024-09-28 01:08:25.6919|INFO|Lively.Core.Watchdog.WatchdogProcess|Cleared watchdog program(s)..
2024-09-28 01:08:25.6919|INFO|Lively.Core.WinDesktopCore|WorkerW initializing..
2024-09-28 01:08:25.7117|INFO|Lively.Core.WinDesktopCore|WorkerW initialized 37684338
2024-09-28 01:08:25.7117|INFO|Lively.Views.WindowMsg.RawInputMsgWindow|Desktop handles updated.
2024-09-28 01:08:25.7117|INFO|Lively.Core.Suspend.Playback|Desktop handles updated.
2024-09-28 01:08:25.7117|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: Music Tunnel | C:\Users\Oscar\AppData\Local\Lively Wallpaper\Library\wallpapers\spfaevge.qza\index.html
2024-09-28 01:08:26.1698|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef4: {"Type":0,"Hwnd":6817302}
2024-09-28 01:08:26.1870|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=1920,Height=1080}
2024-09-28 01:08:26.2057|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 13440
2024-09-28 01:08:26.4143|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef4: {"Type":2,"Success":true}
2024-09-28 01:08:26.4299|INFO|Lively.Core.Watchdog.WatchdogProcess|Removing program to watchdog: 13440
2024-09-28 01:08:26.8493|ERROR|Lively.Core.WinDesktopCore|WorkerW destroyed.
2024-09-28 01:08:26.8493|INFO|Lively.Core.WinDesktopCore|Restarting wallpaper service..
2024-09-28 01:08:26.8493|INFO|Lively.Core.WinDesktopCore|WorkerW initializing..
2024-09-28 01:08:26.8493|INFO|Lively.Core.WinDesktopCore|WorkerW initialized 2491130
2024-09-28 01:08:26.8493|INFO|Lively.Views.WindowMsg.RawInputMsgWindow|Desktop handles updated.
2024-09-28 01:08:26.8493|INFO|Lively.Core.Suspend.Playback|Desktop handles updated.

**Comment by wdskdl** [comment]
I had the same problem

**Comment by danutzzzzz** [comment]
I just downloaded Lively and am instantly facing this issue.

Installed through Windows store

`Microsoft Windows [Version 10.0.26100.2314]`

**Comment by danutzzzzz** [comment]
[lively_log_20241125_152506.zip](https://github.com/user-attachments/files/17905153/lively_log_20241125_152506.zip)

**Comment by rocksdanister** [comment]
dup: https://github.com/rocksdanister/lively/discussions/2464

**Comment by ali-anigma** [comment]
Currently I am facing also same issue. did anybody got fix this bug?
