### ISSUE TITLE
Only seeing wallpaper on primary monitor

### ISSUE THREAD

**Issue by mrbean76** [rocksdanister/lively#2438]
**Describe the bug**
video only showing on main monitor, not on 2nd monitor

**To Reproduce**
1. downloaded wallpaper from adobe - .mov file
2. set as background
3. see background only on my main monitor, not on my 2nd monitor

**Expected behavior**
See video on both monitors

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 11 24H2

**Additional context**

**Log file (Important)**
2024-10-20 21:23:43.2111|INFO|Lively.App|
Lively v2.1.0.9 x64 desktop-bridge en-GB
OS: Microsoft Windows 11 Pro 10.0.26100
CPU: AMD Ryzen 9 7950X3D 16-Core Processor
GPU: NVIDIA GeForce RTX 4070 SUPER

2024-10-20 21:23:43.2815|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\prash\AppData\Local\Lively Wallpaper\Settings.json'.
File name: 'C:\Users\prash\AppData\Local\Lively Wallpaper\Settings.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath)
   at Lively.Services.JsonUserSettingsService.Load[T]()
2024-10-20 21:23:43.3417|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\prash\AppData\Local\Lively Wallpaper\AppRules.json'.
File name: 'C:\Users\prash\AppData\Local\Lively Wallpaper\AppRules.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath)
   at Lively.Services.JsonUserSettingsService.Load[T]()
2024-10-20 21:23:43.3417|ERROR|Lively.Services.JsonUserSettingsService|System.IO.FileNotFoundException: Could not find file 'C:\Users\prash\AppData\Local\Lively Wallpaper\WallpaperLayout.json'.
File name: 'C:\Users\prash\AppData\Local\Lively Wallpaper\WallpaperLayout.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.OpenText(String path)
   at Lively.Common.Helpers.Storage.JsonStorage`1.LoadData(String filePath)
   at Lively.Services.JsonUserSettingsService.Load[T]()
2024-10-20 21:23:43.4993|INFO|Lively.Helpers.WindowsStartup|Startup is disabled
2024-10-20 21:23:43.5088|INFO|Lively.Helpers.WindowsStartup|Request to enable startup Enabled
2024-10-20 21:23:43.5088|INFO|Lively.Core.WinDesktopCore|WorkerW initializing..
2024-10-20 21:23:43.5490|INFO|Lively.Core.WinDesktopCore|WorkerW initialized 16977824
2024-10-20 21:23:43.5490|INFO|Lively.Core.WinDesktopCore|Hooking WorkerW events..
2024-10-20 21:23:43.7186|INFO|Lively.Views.WindowMsg.RawInputMsgWindow|Desktop handles updated.
2024-10-20 21:23:43.7186|INFO|Lively.Core.Suspend.Playback|Desktop handles updated.
2024-10-20 21:23:57.9156|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: AdobeStock_370096161 | C:\Users\prash\Downloads\AdobeStock_370096161.mov
2024-10-20 21:23:57.9156|INFO|Lively.Core.Watchdog.WatchdogProcess|Starting watchdog service...
2024-10-20 21:23:58.0379|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0:  (+) Video --vid=1 (*) (prores 3840x2160 29.970fps)
2024-10-20 21:23:58.6820|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv0: VO: [gpu] 3840x2160 yuv422p10
2024-10-20 21:24:07.8649|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=0,Y=0,Width=2560,Height=1600}
2024-10-20 21:24:07.8961|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 50116
2024-10-20 21:24:23.2715|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: AdobeStock_370096161 | C:\Users\prash\Downloads\AdobeStock_370096161.mov
2024-10-20 21:24:23.3029|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv1:  (+) Video --vid=1 (*) (prores 3840x2160 29.970fps)
2024-10-20 21:24:23.9641|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv1: VO: [gpu] 3840x2160 yuv422p10
2024-10-20 21:24:24.0612|INFO|Lively.Core.Watchdog.WatchdogProcess|Removing program to watchdog: 50116
2024-10-20 21:24:24.0612|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=0,Y=0,Width=2560,Height=1600}
2024-10-20 21:24:24.1016|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 50788
2024-10-20 21:24:35.1181|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv2:  (+) Video --vid=1 (*) (prores 3840x2160 29.970fps)
2024-10-20 21:24:35.7683|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv2: VO: [gpu] 3840x2160 yuv422p10
2024-10-20 21:26:03.7579|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: Fluids | C:\Users\prash\AppData\Local\Lively Wallpaper\Library\wallpapers\0wj1biqk.f41\index.html
2024-10-20 21:26:05.5982|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef0: {"Type":0,"Hwnd":657054}
2024-10-20 21:26:05.6254|INFO|Lively.Core.Watchdog.WatchdogProcess|Removing program to watchdog: 50788
2024-10-20 21:26:05.6254|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=0,Y=0,Width=2560,Height=1600}
2024-10-20 21:26:05.6626|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 29892
2024-10-20 21:26:06.2875|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef0: {"Type":2,"Success":true}
2024-10-20 21:26:26.9106|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: AdobeStock_370096161 | C:\Users\prash\Downloads\AdobeStock_370096161.mov
2024-10-20 21:26:26.9409|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv3:  (+) Video --vid=1 (*) (prores 3840x2160 29.970fps)
2024-10-20 21:26:27.5585|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv3: VO: [gpu] 3840x2160 yuv422p10
2024-10-20 21:26:27.6592|INFO|Lively.Core.Watchdog.WatchdogProcess|Removing program to watchdog: 29892
2024-10-20 21:26:27.6592|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=0,Y=0,Width=2560,Height=1600}
2024-10-20 21:26:27.7028|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 49188
2024-10-20 21:27:22.9556|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: AdobeStock_370096161 | C:\Users\prash\Downloads\AdobeStock_370096161.mov
2024-10-20 21:27:22.9895|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv4:  (+) Video --vid=1 (*) (prores 3840x2160 29.970fps)
2024-10-20 21:27:23.6142|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv4: VO: [gpu] 3840x2160 yuv422p10
2024-10-20 21:27:23.7246|INFO|Lively.Core.Watchdog.WatchdogProcess|Removing program to watchdog: 49188
2024-10-20 21:27:23.7246|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=0,Y=0,Width=2560,Height=1600}
2024-10-20 21:27:23.7560|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 3852
2024-10-20 21:27:43.9792|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: Matrix Rain Customizable | C:\Users\prash\AppData\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2\index.html
2024-10-20 21:27:45.3422|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef1: {"Type":0,"Hwnd":1576032}
2024-10-20 21:27:45.3597|INFO|Lively.Core.Watchdog.WatchdogProcess|Removing program to watchdog: 3852
2024-10-20 21:27:45.3597|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=0,Y=0,Width=2560,Height=1600}
2024-10-20 21:27:45.3833|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 47340
2024-10-20 21:27:45.7221|INFO|Lively.Core.Wallpapers.WebCefSharpProcess|Cef1: {"Type":2,"Success":true}
2024-10-20 21:27:59.0019|INFO|Lively.Core.WinDesktopCore|Setting wallpaper: AdobeStock_370096161 | C:\Users\prash\Downloads\AdobeStock_370096161.mov
2024-10-20 21:27:59.0324|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv5:  (+) Video --vid=1 (*) (prores 3840x2160 29.970fps)
2024-10-20 21:27:59.6246|INFO|Lively.Core.Wallpapers.VideoMpvPlayer|Mpv5: VO: [gpu] 3840x2160 yuv422p10
2024-10-20 21:27:59.7192|INFO|Lively.Core.Watchdog.WatchdogProcess|Removing program to watchdog: 47340
2024-10-20 21:27:59.7234|INFO|Lively.Core.WinDesktopCore|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=0,Y=0,Width=2560,Height=1600}
2024-10-20 21:27:59.7575|INFO|Lively.Core.Watchdog.WatchdogProcess|Adding program to watchdog: 3028

**Comment by rocksdanister** [comment]
Screen configuration
https://github.com/rocksdanister/lively/wiki/Getting-Started

**Comment by mrbean76** [comment]
I have followed all steps in the screen configuration and the issue is still there.  @rocksdanister

**Comment by rocksdanister** [comment]
I am subbed to all issues, no need to ping.

Your log says it's setting wallpaper to a single display, how did you try to set wallpaper in screen configuration ? Does duplicate, span etc work?

**Comment by mrbean76** [comment]
Hi, sorry I just used right click and then set. I didn't see the icon where you can select the monitor. So you can mark as resolved. Thanks :-)
