### ISSUE TITLE
Fluids v2 leads to complications with Python psutils module

### ISSUE THREAD

**Issue by tobischiebel** [rocksdanister/lively#393]
**Describe the bug**
Python scripts playing with processes (ids), in this case with psutils, seem to be broken whenever Fluids v2 is set as lively wallpaper.

Further on, if such a script is currently running, the lively windows store app does not start at all (logs attached).

**To Reproduce**

First of all, yes I know, executing other peoples random python scripts may not be your favorite thing to do... my example at which I encountered the bug is a small script which toggles windows mute on the Spotify process whenever the window title is not some song title etc. Check it out before you run it, if you don't trust me on that (you will probably have done so already) :)

1. Set Fluids v2 as wallpaper.
2. Run the script
3. See python error

OR

1. Run the script
2. Try to run Lively
3. See the error (it won't start)

**Expected behavior**
The Python script should run normally (it does when selecting other wallpapers, I haven't tested all of them, but it works with Sphere [Customisable] for example).
If this is just a mistake in my python code I am very sorry and apologize for the inconvenience, I just thought I might share this issue here as it seems like it is a problem caused by the specific wallpaper.

OR

Lively should open up normally.

**Screenshots/Video**
If applicable, add screenshots/video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Fluids v2

**Additional context**

**Log file (Important)**
Attached [lively_log_20210326_124300.zip](https://github.com/rocksdanister/lively/files/6211521/lively_log_20210326_124300.zip)

This is the output my python script produces when ran while Fluids v2 is currently running:

```Traceback (most recent call last):
  File "C:\Users\<UserName>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psutil\_common.py", line 447, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<UserName>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psutil\_pswindows.py", line 679, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\Users\<UserName>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psutil\_common.py", line 450, in wrapper
    return fun(self)
  File "C:\Users\<UserName>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psutil\_pswindows.py", line 766, in exe
    exe = cext.proc_exe(self.pid)
PermissionError: [WinError 24] Das Programm hat einen Befehl ausgegeben, aber die Befehlslänge ist falsch: '(originated from NtQuerySystemInformation)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/<UserName>/OneDrive - stud.uni-stuttgart.de/Projekte/SpotifyAdMute/main.py", line 89, in <module>
    main()
  File "c:/Users/<UserName>/OneDrive - stud.uni-stuttgart.de/Projekte/SpotifyAdMute/main.py", line 55, in main
    if session.Process and session.Process.name().lower() == "spotify.exe":
  File "C:\Users\<UserName>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psutil\__init__.py", line 617, in name
    name = self._proc.name()
  File "C:\Users\<UserName>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psutil\_pswindows.py", line 750, in name
    return os.path.basename(self.exe())
  File "C:\Users\<UserName>\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psutil\_pswindows.py", line 681, in wrapper
    raise convert_oserror(err, pid=self.pid, name=self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=17660)```

**Comment by rocksdanister** [comment]
You did not share the python script.. ~~also the german error messages are not welcoming :/~~

**Comment by tobischiebel** [comment]
Oh, I am sorry, the Python script probably went missing as I tried to attach it as a file (which is not supported), so here you go:

[main.zip](https://github.com/rocksdanister/lively/files/6214741/main.zip)

```Python
import win32gui
import win32process
import time
from pycaw.pycaw import AudioUtilities


# True whenever Spotfiy is muted, else False
muted = False

# Timer for ad length
start_time = 0


# Enumerate all window titles for a given process id (pid)
def enum_window_titles(pid=None):

    def callback(handle, data):
        if win32process.GetWindowThreadProcessId(handle)[1] == pid:
            titles.append(win32gui.GetWindowText(handle))

    titles = []
    win32gui.EnumWindows(callback, None)

    return titles


# Toggles mute of the specified (current) Spotify session as described in param mute
def toggle_mute_spotify(session, mute):

    global muted, start_time

    volume = session.SimpleAudioVolume

    if mute:
        volume.SetMute(1, None)
        muted = True
        print("[" + time.strftime("%d. %b %Y %H:%M:%S",
                                  time.localtime()) + "] Muted Spotify!")
        start_time = int(round(time.time() * 1000))
    else:
        volume.SetMute(0, None)
        muted = False
        ad_length = (int(round(time.time() * 1000)) - start_time) / 1000
        print("[" + time.strftime("%d. %b %Y %H:%M:%S", time.localtime()) + "] Unmuted Spotify after " +
              str(ad_length) + "s!")


def main():

    found = False

    # Find Spotify process (its pid and audio session)
    # [!] Must have played audio once before process can be found.
    for session in AudioUtilities.GetAllSessions():
        if session.Process and session.Process.name().lower() == "spotify.exe":
            pid = session.Process.pid
            spotify = session
            found = True
            break

    if found:
        print("[+] Spotify process found. Launched successfully!")
        print("".center(60, "_"))
    else:
        print("[!] Spotify process cannot be found!\n    It is either currently not running or hasn't played audio at least once since it launched!")
        input()
        exit()

    try:

        # Continuously wait for window title of Spotify to change to "Advertisment"
        # to then mute process (and unmute again after)
        while True:

            windows = enum_window_titles(pid)
            if ("Advertisement" in windows) or ("Spotify Free" in windows):
                if not muted:
                    toggle_mute_spotify(spotify, True)
            elif muted:
                time.sleep(0.5)
                toggle_mute_spotify(spotify, False)

    # Make sure Spotify is unmuted on exit
    finally:
        toggle_mute_spotify(spotify, False)


if __name__ == "__main__":
    main()
```


Also, ```PermissionError: [WinError 24] Das Programm hat einen Befehl ausgegeben, aber die Befehlslänge ist falsch: '(originated from NtQuerySystemInformation)'``` just says something like "The program issued a command, but the command length is incorrect"

**Comment by rocksdanister** [comment]
```
[+] Spotify process found. Launched successfully!
____________________________________________________________
[31. Mar 2021 13:17:25] Muted Spotify!
[31. Mar 2021 13:17:29] Unmuted Spotify after 3.377s!
```
Not crashing for me with Fluid running :/

**Comment by tobischiebel** [comment]
Okay, thank you for testing anyways, I'm sorry for wasting your time. Love your work, keep it up :)
