### ISSUE TITLE
"oops..looks like something went wrong."

### ISSUE THREAD

**Issue by ICYBAWSS** [rocksdanister/lively#531]
"oops..looks like something went wrong."
here is log:
2021-06-02 08:12:01.6367|INFO|livelywpf.NLogger|
Lively v1.5.0.0 en-US 64Bit:False MSIX:True
OS: Microsoft Windows 10 Home 10.0.19042
CPU: Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz
GPU: Intel(R) UHD Graphics

2021-06-02 08:12:02.0963|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\rayha\AppData\Local\Lively Wallpaper\Library\wallpapers\0wj1biqk.f41\fluid.html webaudio
2021-06-02 08:12:02.1175|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\rayha\AppData\Local\Lively Wallpaper\Library\wallpapers\4kgcos4n.kal\waves.html web
2021-06-02 08:12:02.1175|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\rayha\AppData\Local\Lively Wallpaper\Library\wallpapers\aahrtq0t.dme\index.html web
2021-06-02 08:12:02.1273|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\rayha\AppData\Local\Lively Wallpaper\Library\wallpapers\gdkyowfb.3tk\eternal_light_version2.mp4 video
2021-06-02 08:12:02.1273|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\rayha\AppData\Local\Lively Wallpaper\Library\wallpapers\iqdvd4pt.jyo\triangle.html web
2021-06-02 08:12:02.1273|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\rayha\AppData\Local\Lively Wallpaper\Library\wallpapers\lgz4xpht.sjn\index.html web
2021-06-02 08:12:02.1273|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\rayha\AppData\Local\Lively Wallpaper\Library\wallpapers\mrn3a0m5.0lk\index.html web
2021-06-02 08:12:02.1408|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\rayha\AppData\Local\Lively Wallpaper\Library\wallpapers\nps35xrp.5eh\jellyfish.html web
2021-06-02 08:12:02.1408|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\rayha\AppData\Local\Lively Wallpaper\Library\wallpapers\ptpcxvcd.hlz\index.html web
2021-06-02 08:12:02.1408|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\rayha\AppData\Local\Lively Wallpaper\Library\wallpapers\rtnm43pj.wyl\index.html web
2021-06-02 08:12:02.1408|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\rayha\AppData\Local\Lively Wallpaper\Library\wallpapers\v44be4yd.a1r\ribbon.html web
2021-06-02 08:12:02.1408|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\rayha\AppData\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2\index.html web
2021-06-02 08:12:02.1527|INFO|livelywpf.LibraryViewModel|Loading Wallpaper (no-file):- https://dvdscreensaver.online url
2021-06-02 08:12:02.1527|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(absolute):- C:\Users\rayha\Downloads\desert-night-2-eccefb9e8cf403d83fe92f5d517e8cf3.jpg picture
2021-06-02 08:12:02.1527|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(absolute):- C:\Users\rayha\Downloads\DVD Screensaver.html web
2021-06-02 08:12:03.3791|INFO|livelywpf.SetupDesktop|Core: Wallpaper input setup=> mouse
2021-06-02 08:12:03.6468|INFO|livelywpf.WindowsStartup|Startup is enabled.
2021-06-02 08:12:03.6564|INFO|livelywpf.WindowsStartup|Startup is enabled.
2021-06-02 08:14:04.6788|INFO|livelywpf.SetupDesktop|Core: Setting Wallpaper=>https:dvdscreensaver.online https://dvdscreensaver.online
2021-06-02 08:14:04.7057|INFO|livelywpf.SetupDesktop|Core Initialized
2021-06-02 08:14:04.7173|INFO|livelywpf.Core.WatchdogProcess|Starting watchdog service..
2021-06-02 08:14:04.9432|ERROR|livelywpf.SetupDesktop|Core: Failed to launch wallpaper=>Failed to start process.
System.ComponentModel.Win32Exception (2): The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at livelywpf.Core.WebProcess.Show()

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/358
