### ISSUE TITLE
When setting wallpaper error occurs.

### ISSUE THREAD

**Issue by FlippedSuit** [rocksdanister/lively#545]
When I try to set a wallpaper the error message pops up and no wallpaper is set. I have checked the wiki, all the solutions there don't work. This is the error code that it gives. How can I fix this. I already uninstalled and reinstalled to see if it would fix it.

2021-06-09 08:08:04.7921|ERROR|livelywpf.SettingsViewModel|System.IO.FileNotFoundException: Could not find file 'C:\Users\willi\AppData\Local\Lively Wallpaper\Settings.json'.
File name: 'C:\Users\willi\AppData\Local\Lively Wallpaper\Settings.json'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at livelywpf.Helpers.JsonStorage`1.LoadData(String filePath)
   at livelywpf.SettingsViewModel..ctor()

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/issues/358
