### ISSUE TITLE
Lively crashes when using Multiplicity

### ISSUE THREAD

**Issue by dankwow** [rocksdanister/lively#575]
**Describe the bug**
When Multiplicity is running alongside Lively Wallpaper, changing to the client machine causes the program to exit, leaving the system tray icon until pointed at.

**To Reproduce**
1. Run Multiplicity while Lively Wallpaper is also running.
2. Attempt to move the mouse to the client by going off the edge of the screen, similar to having two monitors.
3. Lively wallpaper closes with no errors
4. See error:

> Faulting application name: livelywpf.exe, version: 1.5.0.0, time stamp: 0x604fdaf2
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1023, time stamp: 0xcbf6f7d1
Exception code: 0xe0434352
Fault offset: 0x0012a6f2
Faulting process id: 0x4358
Faulting application start time: 0x01d769915bb9986a
Faulting application path: C:\Program Files\WindowsApps\12030rocksdanister.LivelyWallpaper_1.0.38.0_x86__97hta09mmv6hy\livelywpf\livelywpf.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 2eaed6ee-18ed-4625-9405-b02be5a14dea
Faulting package full name: 12030rocksdanister.LivelyWallpaper_1.0.38.0_x86__97hta09mmv6hy

**Expected behavior**
Expected to control another PC while Lively Wallpaper continues executing.

**Screenshots/Video**
N/A.

**Desktop (please complete the following information):**
 - OS: [Windows 10, 21H1]
- Which wallpaper was running at the time if any. [Fluids V2]

**Additional context**
Lively Wallpaper is also running on the client PC and does not crash when exiting the client, returning to the host.

**Log file (Important)**

```2021-06-25 03:21:38.6108|ERROR|livelywpf.App|Unhandled exception in livelywpf v1.5.0.0
Linearstar.Windows.RawInput.Native.Win32ErrorException: Invalid access to memory location.

   at Linearstar.Windows.RawInput.Native.User32.GetRawInputDataHeader(RawInputHandle rawInput)
   at Linearstar.Windows.RawInput.RawInputData.FromHandle(RawInputHandle rawInput)
   at livelywpf.Core.RawInputDX.Hook(IntPtr hwnd, Int32 msg, IntPtr wparam, IntPtr lparam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2021-06-25 03:21:38.6108|ERROR|livelywpf.App|Unhandled exception in livelywpf v1.5.0.0
Linearstar.Windows.RawInput.Native.Win32ErrorException: Invalid access to memory location.

   at Linearstar.Windows.RawInput.Native.User32.GetRawInputDataHeader(RawInputHandle rawInput)
   at Linearstar.Windows.RawInput.RawInputData.FromHandle(RawInputHandle rawInput)
   at livelywpf.Core.RawInputDX.Hook(IntPtr hwnd, Int32 msg, IntPtr wparam, IntPtr lparam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at livelywpf.Program.Main()
```

[lively_log_20210625_033041.zip](https://github.com/rocksdanister/lively/files/6714409/lively_log_20210625_033041.zip)

**Comment by rocksdanister** [comment]
See if it still crashes if `Settings -> Wallpaper -> Interaction -> Wallpaper Input -> Off`

**Comment by dankwow** [comment]
Thanks for the help, It does not crash with this option.

**Comment by neozizen** [comment]
I have exact same issue... however, when I set Wallpaper Input to "Off" it does not help.  Anytime I move my cursor to the secondary computer and wait a couple seconds, Lively will crash.  I'm on Windows 11 so that must be the issue here.  I tried setting to "Keyboard" and still crashes.

**Comment by f3yc0w** [comment]
> I have exact same issue... however, when I set Wallpaper Input to "Off" it does not help. Anytime I move my cursor to the secondary computer and wait a couple seconds, Lively will crash. I'm on Windows 11 so that must be the issue here. I tried setting to "Keyboard" and still crashes.

I am still having this issue as of Feb 4 of 2024.

**Comment by dankwow** [comment]
Since putting wallpaper input to off effectively disables the program, I would also say I have the same issue. I'm still on windows 10.

**Comment by rocksdanister** [comment]
Old version used to turn off the hook when input is turned OFF, with the new version this does not happen since its used to detect motion during screensaver mode.

I reported the issue to the library author, will wait and see.
