### ISSUE TITLE
Lively Fails when Changing Web Engine

### ISSUE THREAD

**Issue by CEbbinghaus** [rocksdanister/lively#617]
**Describe the bug**
Lively Crashes when switching to MS Edge

**To Reproduce**
* Open Web wallpaper in Chrome CEF
* Change Rendering Engine to MS Edge
* Lively Reports crash with error Log.
(selecting any non-web wallpaper works. but selecting any of the web wallpapers shows the same alert)

**Expected behavior**
Switch to different Browser reloads the same wallpapers showing correctly

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/31423391/125762955-da7220bf-a909-4333-9899-29044a1ef69e.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 19042.1083
- Any Web Wallpaper

**Additional context**
N/A

**Log file (Important)**
```
2021-07-15 11:41:32.0717|INFO|livelywpf.NLogger|
Lively v1.7.0.2 x64 desktop-native en-AU
OS: Microsoft Windows 10 Pro 10.0.19042
CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
GPU: NVIDIA GeForce GTX 1070

2021-07-15 11:41:32.6933|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\0wj1biqk.f41\fluid.html webaudio
2021-07-15 11:41:32.7032|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\4kgcos4n.kal\waves.html web
2021-07-15 11:41:32.7032|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\aahrtq0t.dme\index.html web
2021-07-15 11:41:32.7170|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\gdkyowfb.3tk\eternal_light_version2.mp4 video
2021-07-15 11:41:32.7170|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\iqdvd4pt.jyo\triangle.html web
2021-07-15 11:41:32.7170|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\lgz4xpht.sjn\index.html web
2021-07-15 11:41:32.7348|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\mrn3a0m5.0lk\index.html web
2021-07-15 11:41:32.7348|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\nps35xrp.5eh\jellyfish.html web
2021-07-15 11:41:32.7477|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\ptpcxvcd.hlz\index.html web
2021-07-15 11:41:32.7477|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\rtnm43pj.wyl\index.html web
2021-07-15 11:41:32.7477|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\v44be4yd.a1r\ribbon.html web
2021-07-15 11:41:32.7674|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2\index.html web
2021-07-15 11:41:33.5957|DEBUG|livelywpf.MainWindow|MainWindow ctor initialized..
2021-07-15 11:41:34.5736|INFO|livelywpf.SetupDesktop|Restoring wallpaper Rain v2 | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\aahrtq0t.dme
2021-07-15 11:41:34.5736|INFO|livelywpf.SetupDesktop|Setting wallpaper: Rain v2 | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\aahrtq0t.dme\index.html
2021-07-15 11:41:34.8407|INFO|livelywpf.SetupDesktop|Core initialized..
2021-07-15 11:41:34.8510|INFO|livelywpf.Core.WatchdogProcess|Starting watchdog service...
2021-07-15 11:41:34.9732|INFO|livelywpf.SetupDesktop|Restoring wallpaper Ripples | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\mrn3a0m5.0lk
2021-07-15 11:41:34.9732|INFO|livelywpf.SetupDesktop|Setting wallpaper: Ripples | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\mrn3a0m5.0lk\index.html
2021-07-15 11:41:36.2658|INFO|livelywpf.Core.WebProcess|Cef0: {"Type":0,"Hwnd":67138}
2021-07-15 11:41:36.3159|INFO|livelywpf.SetupDesktop|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=3840,Height=2160}
2021-07-15 11:41:36.3379|INFO|livelywpf.Core.WebProcess|Cef1: {"Type":0,"Hwnd":67148}
2021-07-15 11:41:36.3483|INFO|livelywpf.Core.WatchdogProcess|Adding program to watchdog: 15848
2021-07-15 11:41:36.4027|INFO|livelywpf.SetupDesktop|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=-1080,Y=-144,Width=1080,Height=1920}
2021-07-15 11:41:36.4104|INFO|livelywpf.Core.WatchdogProcess|Adding program to watchdog: 16064
2021-07-15 11:41:37.3804|INFO|livelywpf.Core.WebProcess|Cef0: {"Type":2,"Success":true}
2021-07-15 11:41:37.8403|INFO|livelywpf.Core.WebProcess|Cef1: {"Type":2,"Success":true}
2021-07-15 14:29:59.6282|INFO|livelywpf.SetupDesktop|Setting wallpaper: The Hill | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\lgz4xpht.sjn\index.html
2021-07-15 14:30:00.3175|INFO|livelywpf.Core.WebProcess|Cef2: {"Type":0,"Hwnd":264476}
2021-07-15 14:30:00.3262|INFO|livelywpf.Core.WatchdogProcess|Removing program to watchdog: 16064
2021-07-15 14:30:00.3262|INFO|livelywpf.SetupDesktop|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=-1080,Y=-144,Width=1080,Height=1920}
2021-07-15 14:30:00.3612|INFO|livelywpf.Core.WatchdogProcess|Adding program to watchdog: 3584
2021-07-15 14:30:01.1210|INFO|livelywpf.Core.WebProcess|Cef2: {"Type":1,"Message":"THREE.WebGLRenderer 79","Category":2}
2021-07-15 14:30:01.9519|INFO|livelywpf.Core.WebProcess|Cef2: {"Type":2,"Success":true}
2021-07-15 14:41:44.2134|INFO|livelywpf.Views.LibraryView|Dropped file=>C:\Users\CEbbi\Downloads\Circle-Audio-Visualizer.zip
2021-07-15 14:41:44.3997|INFO|livelywpf.LibraryViewModel|Loading Wallpaper(relative):- C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\lshmziag.soi\index.html webaudio
2021-07-15 14:41:48.0735|INFO|livelywpf.SetupDesktop|Setting wallpaper: Circle Audio Visualizer | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\lshmziag.soi\index.html
2021-07-15 14:41:48.7414|INFO|livelywpf.Core.WebProcess|Cef3: {"Type":0,"Hwnd":1772150}
2021-07-15 14:41:48.7617|INFO|livelywpf.Core.WatchdogProcess|Removing program to watchdog: 3584
2021-07-15 14:41:48.7617|INFO|livelywpf.SetupDesktop|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=-1080,Y=-144,Width=1080,Height=1920}
2021-07-15 14:41:48.7923|INFO|livelywpf.Core.WatchdogProcess|Adding program to watchdog: 7208
2021-07-15 14:41:49.0331|INFO|livelywpf.Core.WebProcess|Cef3: {"Type":2,"Success":true}
2021-07-15 14:41:50.4688|INFO|livelywpf.SetupDesktop|Setting wallpaper: Medusae | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\nps35xrp.5eh\jellyfish.html
2021-07-15 14:41:51.0073|INFO|livelywpf.Core.WebProcess|Cef4: {"Type":0,"Hwnd":198942}
2021-07-15 14:41:51.0073|INFO|livelywpf.Core.WatchdogProcess|Removing program to watchdog: 7208
2021-07-15 14:41:51.0073|INFO|livelywpf.SetupDesktop|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=-1080,Y=-144,Width=1080,Height=1920}
2021-07-15 14:41:51.0595|INFO|livelywpf.Core.WatchdogProcess|Adding program to watchdog: 6780
2021-07-15 14:41:51.0595|INFO|livelywpf.SetupDesktop|Setting wallpaper: Circle Audio Visualizer | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\lshmziag.soi\index.html
2021-07-15 14:41:51.4366|INFO|livelywpf.Core.WebProcess|Cef4: {"Type":2,"Success":true}
2021-07-15 14:41:51.4445|INFO|livelywpf.Core.WebProcess|Cef4: {"Type":1,"Message":"THREE.WebGLRenderer 72","Category":2}
2021-07-15 14:41:51.5771|INFO|livelywpf.Core.WebProcess|Cef4: {"Type":1,"Message":"Particulate.js 0.3.2","Category":2}
2021-07-15 14:41:51.8458|INFO|livelywpf.Core.WebProcess|Cef5: {"Type":0,"Hwnd":1247838}
2021-07-15 14:41:51.8458|INFO|livelywpf.Core.WatchdogProcess|Removing program to watchdog: 6780
2021-07-15 14:41:51.8543|INFO|livelywpf.SetupDesktop|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=-1080,Y=-144,Width=1080,Height=1920}
2021-07-15 14:41:51.8967|INFO|livelywpf.Core.WatchdogProcess|Adding program to watchdog: 24268
2021-07-15 14:41:52.1784|INFO|livelywpf.Core.WebProcess|Cef5: {"Type":2,"Success":true}
2021-07-15 14:42:04.1601|INFO|livelywpf.SetupDesktop|Setting wallpaper: The Hill | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\lgz4xpht.sjn\index.html
2021-07-15 14:42:04.7787|INFO|livelywpf.Core.WebProcess|Cef6: {"Type":0,"Hwnd":395586}
2021-07-15 14:42:04.7787|INFO|livelywpf.Core.WatchdogProcess|Removing program to watchdog: 24268
2021-07-15 14:42:04.7787|INFO|livelywpf.SetupDesktop|Sending wallpaper(Screen): \\.\DISPLAY2 | {X=-1080,Y=-144,Width=1080,Height=1920}
2021-07-15 14:42:04.8249|INFO|livelywpf.Core.WatchdogProcess|Adding program to watchdog: 9916
2021-07-15 14:42:05.1070|INFO|livelywpf.Core.WebProcess|Cef6: {"Type":1,"Message":"THREE.WebGLRenderer 79","Category":2}
2021-07-15 14:42:05.9653|INFO|livelywpf.Core.WebProcess|Cef6: {"Type":2,"Success":true}
2021-07-15 15:07:03.3861|INFO|livelywpf.SetupDesktop|Setting wallpaper: Circle Audio Visualizer | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\lshmziag.soi\index.html
2021-07-15 15:07:04.1029|INFO|livelywpf.Core.WebProcess|Cef7: {"Type":0,"Hwnd":199662}
2021-07-15 15:07:04.1158|INFO|livelywpf.Core.WatchdogProcess|Removing program to watchdog: 15848
2021-07-15 15:07:04.1158|INFO|livelywpf.SetupDesktop|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=3840,Height=2160}
2021-07-15 15:07:04.1575|INFO|livelywpf.Core.WatchdogProcess|Adding program to watchdog: 23448
2021-07-15 15:07:04.4131|INFO|livelywpf.Core.WebProcess|Cef7: {"Type":2,"Success":true}
2021-07-15 15:07:12.0440|INFO|livelywpf.SetupDesktop|Setting wallpaper: Rain v2 | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\aahrtq0t.dme\index.html
2021-07-15 15:07:12.5839|INFO|livelywpf.Core.WebProcess|Cef8: {"Type":0,"Hwnd":132674}
2021-07-15 15:07:12.5891|INFO|livelywpf.Core.WatchdogProcess|Removing program to watchdog: 23448
2021-07-15 15:07:12.5891|INFO|livelywpf.SetupDesktop|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=3840,Height=2160}
2021-07-15 15:07:12.6356|INFO|livelywpf.Core.WatchdogProcess|Adding program to watchdog: 20072
2021-07-15 15:07:12.8620|INFO|livelywpf.Core.WebProcess|Cef8: {"Type":2,"Success":true}
2021-07-15 16:51:40.9218|INFO|livelywpf.SetupDesktop|Setting wallpaper: Circle Audio Visualizer | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\lshmziag.soi\index.html
2021-07-15 16:51:41.5726|INFO|livelywpf.Core.WebProcess|Cef9: {"Type":0,"Hwnd":1641046}
2021-07-15 16:51:41.5726|INFO|livelywpf.Core.WatchdogProcess|Removing program to watchdog: 20072
2021-07-15 16:51:41.5726|INFO|livelywpf.SetupDesktop|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=3840,Height=2160}
2021-07-15 16:51:41.6287|INFO|livelywpf.Core.WatchdogProcess|Adding program to watchdog: 24928
2021-07-15 16:51:41.8815|INFO|livelywpf.Core.WebProcess|Cef9: {"Type":2,"Success":true}
2021-07-15 17:02:49.3804|INFO|livelywpf.SettingsViewModel|Restarting wallpaper:videostream
2021-07-15 17:02:49.3811|INFO|livelywpf.SettingsViewModel|Restarting wallpaper:video
2021-07-15 17:02:49.3811|INFO|livelywpf.SettingsViewModel|Restarting wallpaper:gif
2021-07-15 17:02:49.3811|INFO|livelywpf.SettingsViewModel|Restarting wallpaper:picture
2021-07-15 17:02:52.3576|INFO|livelywpf.SettingsViewModel|Restarting wallpaper:videostream
2021-07-15 17:02:52.3576|INFO|livelywpf.SettingsViewModel|Restarting wallpaper:video
2021-07-15 17:02:52.3576|INFO|livelywpf.SettingsViewModel|Restarting wallpaper:gif
2021-07-15 17:02:52.3576|INFO|livelywpf.SettingsViewModel|Restarting wallpaper:picture
2021-07-15 19:09:30.4062|INFO|livelywpf.SettingsViewModel|Restarting wallpaper:web
2021-07-15 19:09:30.4062|INFO|livelywpf.Core.WatchdogProcess|Removing program to watchdog: 9916
2021-07-15 19:09:30.4127|INFO|livelywpf.SetupDesktop|Setting wallpaper: The Hill | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\lgz4xpht.sjn\index.html
2021-07-15 19:09:30.7375|INFO|livelywpf.SettingsViewModel|Restarting wallpaper:webaudio
2021-07-15 19:09:30.7375|INFO|livelywpf.Core.WatchdogProcess|Removing program to watchdog: 24928
2021-07-15 19:09:30.7375|INFO|livelywpf.SetupDesktop|Setting wallpaper: Circle Audio Visualizer | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\lshmziag.soi\index.html
2021-07-15 19:09:30.7986|INFO|livelywpf.SettingsViewModel|Restarting wallpaper:url
2021-07-15 19:09:30.8645|ERROR|livelywpf.SetupDesktop|Failed launching wallpaper: WebView initialization fail.
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at livelywpf.WebView2Element.InitializeWebView() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Views\Wallpapers\WebView2Element.xaml.cs:line 43
   at livelywpf.Core.WebEdge.Show() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\Wallpapers\WebEdge.cs:line 160
2021-07-15 19:09:34.6646|ERROR|livelywpf.SetupDesktop|Failed launching wallpaper: WebView initialization fail.
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at livelywpf.WebView2Element.InitializeWebView() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Views\Wallpapers\WebView2Element.xaml.cs:line 43
   at livelywpf.Core.WebEdge.Show() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\Wallpapers\WebEdge.cs:line 160
2021-07-15 19:09:50.8673|INFO|livelywpf.SetupDesktop|Setting wallpaper: Eternal Light | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\gdkyowfb.3tk\eternal_light_version2.mp4
2021-07-15 19:09:51.7556|INFO|livelywpf.Core.VideoMpvPlayer|Mpv0:  (+) Video --vid=1 (*) (h264 1920x1080 24.000fps)
2021-07-15 19:09:52.0094|INFO|livelywpf.Core.VideoMpvPlayer|Mpv0: Using hardware decoding (d3d11va).
2021-07-15 19:09:52.0094|INFO|livelywpf.Core.VideoMpvPlayer|Mpv0: VO: [gpu] 1920x1080 d3d11[nv12]
2021-07-15 19:09:52.0554|INFO|livelywpf.SetupDesktop|Sending wallpaper(Screen): \\.\DISPLAY1 | {X=0,Y=0,Width=3840,Height=2160}
2021-07-15 19:09:52.0554|INFO|livelywpf.Core.WatchdogProcess|Adding program to watchdog: 21264
2021-07-15 19:09:58.0700|INFO|livelywpf.SetupDesktop|Setting wallpaper: Circle Audio Visualizer | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\lshmziag.soi\index.html
2021-07-15 19:09:58.1728|ERROR|livelywpf.SetupDesktop|Failed launching wallpaper: WebView initialization fail.
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at livelywpf.WebView2Element.InitializeWebView() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Views\Wallpapers\WebView2Element.xaml.cs:line 43
   at livelywpf.Core.WebEdge.Show() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\Wallpapers\WebEdge.cs:line 160
2021-07-15 19:10:00.2778|INFO|livelywpf.SetupDesktop|Setting wallpaper: Matrix Rain Customizable | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\xn0quq52.bq2\index.html
2021-07-15 19:10:00.3825|ERROR|livelywpf.SetupDesktop|Failed launching wallpaper: WebView initialization fail.
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at livelywpf.WebView2Element.InitializeWebView() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Views\Wallpapers\WebView2Element.xaml.cs:line 43
   at livelywpf.Core.WebEdge.Show() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\Wallpapers\WebEdge.cs:line 160
2021-07-15 19:10:01.8535|INFO|livelywpf.SetupDesktop|Setting wallpaper: Medusae | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\nps35xrp.5eh\jellyfish.html
2021-07-15 19:10:01.9309|ERROR|livelywpf.SetupDesktop|Failed launching wallpaper: WebView initialization fail.
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at livelywpf.WebView2Element.InitializeWebView() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Views\Wallpapers\WebView2Element.xaml.cs:line 43
   at livelywpf.Core.WebEdge.Show() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\Wallpapers\WebEdge.cs:line 160
2021-07-15 19:10:03.2823|INFO|livelywpf.SetupDesktop|Setting wallpaper: Ripples | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\mrn3a0m5.0lk\index.html
2021-07-15 19:10:03.3702|ERROR|livelywpf.SetupDesktop|Failed launching wallpaper: WebView initialization fail.
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at livelywpf.WebView2Element.InitializeWebView() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Views\Wallpapers\WebView2Element.xaml.cs:line 43
   at livelywpf.Core.WebEdge.Show() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\Wallpapers\WebEdge.cs:line 160
2021-07-15 19:10:04.5443|INFO|livelywpf.SetupDesktop|Setting wallpaper: The Hill | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\lgz4xpht.sjn\index.html
2021-07-15 19:10:04.6677|ERROR|livelywpf.SetupDesktop|Failed launching wallpaper: WebView initialization fail.
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at livelywpf.WebView2Element.InitializeWebView() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Views\Wallpapers\WebView2Element.xaml.cs:line 43
   at livelywpf.Core.WebEdge.Show() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\Wallpapers\WebEdge.cs:line 160
2021-07-15 19:15:45.0834|INFO|livelywpf.SetupDesktop|Setting wallpaper: Circle Audio Visualizer | C:\Users\CEbbi\AppData\Local\Lively Wallpaper\Library\wallpapers\lshmziag.soi\index.html
2021-07-15 19:15:45.2287|ERROR|livelywpf.SetupDesktop|Failed launching wallpaper: WebView initialization fail.
Microsoft.Web.WebView2.Core.WebView2RuntimeNotFoundException: Couldn't find a compatible Webview2 Runtime installation to host WebViews.
 ---> System.IO.FileNotFoundException: The system cannot find the file specified. (0x80070002)
   --- End of inner exception stack trace ---
   at Microsoft.Web.WebView2.Core.CoreWebView2Environment.CreateAsync(String browserExecutableFolder, String userDataFolder, CoreWebView2EnvironmentOptions options)
   at livelywpf.WebView2Element.InitializeWebView() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Views\Wallpapers\WebView2Element.xaml.cs:line 43
   at livelywpf.Core.WebEdge.Show() in C:\Users\rocks\source\repos\livelywpf\livelywpf\Core\Wallpapers\WebEdge.cs:line 160

```

**Comment by rocksdanister** [comment]
https://github.com/rocksdanister/lively/wiki/Web-Guide-I-:-Cef#webview2-microsoft-edge
