### ISSUE TITLE
Video wallpapers don't work / Windows N

### ISSUE THREAD

**Issue by alrinach62** [rocksdanister/lively#717]
hello, I can't add new wallpaper. nothing works. I copy paste or I copy the link, an error message appears.

look at the picture below

![image](https://user-images.githubusercontent.com/90425254/132770528-6e908e7a-4300-45a1-aa9b-8f89acab4a0c.png)

log files:
2021-09-10 00:04:20.0749|ERROR|livelywpf.SettingsViewModel|System.IO.FileNotFoundException: Could not find file 'C:\Users\Clément\AppData\Local\Lively Wallpaper\Settings.json'.
File name: 'C:\Users\Clément\AppData\Local\Lively Wallpaper\Settings.json'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at livelywpf.Helpers.JsonStorage`1.LoadData(String filePath)
   at livelywpf.SettingsViewModel..ctor()

[

**Comment by rocksdanister** [comment]
Attach the logfile instead of copy pasting.

**Comment by alrinach62** [comment]
[
[lively_log_20210911_100948.zip](https://github.com/rocksdanister/lively/files/7147437/lively_log_20210911_100948.zip)
](url)

**Comment by rocksdanister** [comment]
**Windows N** require additional codec installation:
https://github.com/rocksdanister/lively/wiki/Video-Guide

**Comment by alrinach62** [comment]
hello after having downloaded the codecs for the N version of microsoft, I have this error which appears when I try to add a wallpaper.

![Capture 2](https://user-images.githubusercontent.com/90425254/132962293-34dfa7b5-3857-4ef4-8d5e-3504766ed27a.PNG)
](url)
[
[lively_log_20210911_234513.zip](https://github.com/rocksdanister/lively/files/7148566/lively_log_20210911_234513.zip)
](url)

**Comment by alrinach62** [comment]
I tried to reinstall it but without effect

**Comment by rocksdanister** [comment]
Can you translate that message to english?
Does changing the videoplayer to wmf in settings work?

**Comment by alrinach62** [comment]
the message ==> could not execute code because MFPLAT.DLL could not be found. re-installing the program may correct this problem.

**Comment by alrinach62** [comment]
i just updated microsoft. I just tried to add a wallpaper and it WORKS !!!
thanks for the help
have a good day
